### ISSUE TITLE
Wrapping VecEnv -- Final (old_obs, act, obs) triple is incorrect.

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#1]
Suppose I am at timestep 5 and I took actions that a triggered a                                                                                                       
transition such that my 0th environment ends its episode. Vec Env implementations of step() will internally reset() the 0th environment and return the observation associated with the episode start instead of the episode end.

The episode end is never returned by step(), so there is no way for me to see it.

**Comment by qxcv** [comment]
Steven's idea for a fix:

> Maybe a good way to change this in stable-baselines/gym without screwing up their reset design is to add a "done_new_obs" item to the info dict returned by vec_env.step().

I think it's very important that we do this. I'll probably do it next week (before working on trajectory-centric algorithms) if someone doesn't get to it before then.

**Comment by AdamGleave** [comment]
Can you open an issue in https://github.com/hill-a/stable-baselines? I agree this is important to fix.

Adding a field in the info dict is reasonable, although has some downsides (no one can use that key any longer, which is probably ok, but more seriously code will start seeing a new key it might not be expecting). An alternative would be to add a property `obs_before_reset` to `VecEnv` which exposes this.

**Comment by qxcv** [comment]
Opened as [#400 in stable-baselines](https://github.com/hill-a/stable-baselines/issues/400).

**Comment by AdamGleave** [comment]
It seems like the other maintainers in Stable Baselines are happy with this change, are either of you planning on making a PR? I can review it and merge it when ready.

**Comment by shwang** [comment]
I'm interested in doing this (mainly because I want to work with stable-baselines on a new-contributor-friendly PR).

My hands are a bit full right now though, so @qxcv should feel free to do it if it's blocking another algo or if he's just itching to code :).

Otherwise, I will submit a PR on this by next Wednesday.

**Comment by AdamGleave** [comment]
Sounds good. I mostly just wanted to check this hadn't been forgotten (or that people assumed I was going to do it). Not blocking me (occassionally ran into it, but always been able to workaround it).

**Comment by qxcv** [comment]
I'm also not going to do it for a while. I don't think it blocks the trajectory-centric algorithms that I planned to implement.

**Comment by qxcv** [comment]
I lied. Looks like this will eventually be fixed in #54, once hill-a/stable-baselines#412 is merged.

**Comment by AdamGleave** [comment]
Can we close this issue now that https://github.com/hill-a/stable-baselines/pull/412 is merged?

**Comment by qxcv** [comment]
We can once #54 is merged, which contains [this fix](https://github.com/HumanCompatibleAI/imitation/pull/54/files#diff-d1c6b2a8ef9c0720ab54f5c6a22ee235) to `rollout.py`.
