### ISSUE TITLE
Upgrade to Sacred 0.8.x

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#109]
Our code currently breaks with anything >0.7.4 because they made config objects non-picklable. We can workaround this via a config attribute to disable their `ReadOnly*`, or by using a helper method. 

See https://github.com/IDSIA/sacred/issues/499 and https://github.com/IDSIA/sacred/pull/508 for some discussion

**Comment by AdamGleave** [comment]
Keep running into problems with parallelism with Sacred 0.7.4: https://github.com/IDSIA/sacred/pull/503

Fixed in 0.8.x, so slightly higher priority to upgrade (although I can work around it for now)

**Comment by shwang** [comment]
@AdamGleave: It seems to me that our serialization errors in `imitation` might not actually be coming from implicitly pickling Configs (as I think you might have mentioned in one of the threads related to this Sacred issue). I didn't realize this until today, but the latest version of Sacred (v0.8) under regular Sacred settings, never passes `dict` into argument-capturing functions any more. It always passes in `ReadOnlyDict`.

At least in `imitation` it looks like the pickle error comes from me trying to forward a `ReadOnlyDict` (which I used to think is just a `dict`) into Ray subprocesses.

**Comment by shwang** [comment]
IIRC in the Adversarial Policies repo you actually pass around pickled configs. For `imitation` it might be sufficient to just convert every `ReadOnlyDict` into a `dict`. (This would be messy though, as we'd have to recursively "unfreeze" the data structure)

**Comment by AdamGleave** [comment]
> @AdamGleave: It seems to me that our serialization errors in `imitation` might not actually be coming from implicitly pickling Configs (as I think you might have mentioned in one of the threads related to this Sacred issue). I didn't realize this until today, but the latest version of Sacred (v0.8) under regular Sacred settings, never passes `dict` into argument-capturing functions any more. It always passes in `ReadOnlyDict`.
> 
> At least in `imitation` it looks like the pickle error comes from me trying to forward a `ReadOnlyDict` (which I used to think is just a `dict`) into Ray subprocesses.

I'm a bit confused what you mean by implicitly pickling configs? My current understanding was the problem is that the arguments Sacred passes in aren't pickleable, and we want to pickle them when sending to other processes (e.g. for Ray). Apologies if I gave a misleading impression. My view is Sacred should not be changing the types of config arguments under the user's feet in this way, which is why I opened the issue, not that it's an insurmountable problem.

I think in adversarial policies I do explicitly cast `ReadOnlyDict` to `dict`, but as you say it's messy, but yes a viable workaround. Sacred also has a config option I believe that disables this whole read-only thing.

**Comment by shwang** [comment]
Thanks for clarifying. My previous (and incorrect) understanding for why `imitation.scripts.parallel` was failing with new Sacred was that somehow Ray was pickling Sacred configs.

I think I thought this because I didn't realize that Sacred was converting captured dict/list arguments into ReadOnlyContainer types.

**Comment by AdamGleave** [comment]
Ah. I think if Ray ended up pickling entire Sacred config objects you'd run
into other issues, e.g. FileStorageObserver's are not pickleable. Which is
why we're quite careful what is in scope in parallel code to avoid
accidentally pickling too much.

**Comment by shwang** [comment]
Presumably the reason they want to use ReadOnlyContainer is because they don't want the configs or containers inside the config to be updated?

Seems like a better way to do captured arguments in ReadOnly mode is to pass recursively "unfrozen" shallow copies of ReadOnlyDict/List into the user functions.
