### ISSUE TITLE
Upload to PyPI?

### ISSUE THREAD

**Issue by qxcv** [HumanCompatibleAI/imitation#120]
Does someone want to upload this package to PyPI? There doesn't seem to be an "imitation" package on PyPI yet, so it makes sense to reserve the name for this one :smile:

(possibly @shwang is the best person to manage PyPI uploads?)

**Comment by shwang** [comment]
I'll do this this week -- plan on uploading a version `0.1` and making a v0.1 release tag / PR on GH.

**Comment by shwang** [comment]
Can't upload our dist until we use a pypi release of stable-baselines (rather than pointing to github repo)

**Comment by qxcv** [comment]
So I don't forget: this should be added to readthedocs when we're ready for a PyPI release.
