### ISSUE TITLE
Stable format for serializing trajectories

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#185]
Currently we (de)serialize trajectories using `imitation.data.types.{save,load}` using Python pickle. This makes it very sensitive to changes in the format, including even relocating modules.

We could write our own (de)serialization logic to make it more stable, and probably also save space on disk.

**Comment by AdamGleave** [comment]
May actually be easiest to save/load `Transitions`, since that's just a few big NumPy arrays. Then write some code to convert between `Transitions` and `Trajectory`. Should not be hard -- the only thing that's not bijective is `info`, but (a) we usually don't want to serialize this anyway, and (b) we should probably add optional `infos` to `Transitions` anyway.

**Comment by shwang** [comment]
Another reason `Transitions` doesn't map directly onto `List[Trajectory]` is that `Transitions` aren't guaranteed to be in timestep or trajectory order (at least as currently documented), so we can't just split them into different Trajectories at every done=True.

It's true that the way that we currently construct `Transitions` from `flatten_trajectories` preserves timestep and trajectory order.

**Comment by shwang** [comment]
One idea is to save `List[Trajectory]` as a `npz`. `npz` supports Dict (we could make each list index an integer key in the dict form).

```python
{
1: dict(obs=..., acts=..., infos=...),
2: ...,

}
```

**Comment by AdamGleave** [comment]
> Another reason `Transitions` doesn't map directly onto `List[Trajectory]` is that `Transitions` aren't guaranteed to be in timestep or trajectory order (at least as currently documented), so we can't just split them into different Trajectories at every done=True.
> 
> It's true that the way that we currently construct `Transitions` from `flatten_trajectories` preserves timestep and trajectory order.

OK, fair point. This seems easy enough to fix though -- we can just add an "in order" flag to `Transitions`, that is set when produced by `flatten_trajectories`, and refuse to convert if this flag is false. Or just have separate `save()` and `load()` functions for `Trajectory`, which internally map to/from `Transitions` and use that `save()` and `load()`, adding some extra metadata to prevent the user calling `Trajectory.load()` on something produced by `Transitions.save()`.

As a digression, I am still a bit confused why your transitions are out-of-order in MineRL by default. It seems like a desirable thing to do when training many algorithms (epoch order can lead to catastrophic forgetting), but it's odd in serialized data. Can't you just load them all, sort them and then save them in sorted order (then shuffle in-memory if/when desired)?

**Comment by AdamGleave** [comment]
> One idea is to save `List[Trajectory]` as a `npz`. `npz` supports Dict (we could make each list index an integer key in the dict form).
> 
> ```python
> {
> 1: dict(obs=..., acts=..., infos=...),
> 2: ...,
> 
> }
> ```

This would work but is less efficient than saving `Transitions`. There's a lot of overhead in each object you store.

And it seems nice to be able to save and load `Transitions` too.

**Comment by shwang** [comment]
> As a digression, I am still a bit confused why your transitions are out-of-order in MineRL by default. It seems like a desirable thing to do when training many algorithms (epoch order can lead to catastrophic forgetting), but it's odd in serialized data. Can't you just load them all, sort them and then save them in sorted order (then shuffle in-memory if/when desired)?

I don't need to do Trajectory serialization for MineRL, at least not for now. The MineRLDataLoader can be not-interleaved between trajectories, but this would make loading video frames much slower (there is 1 worker process per trajectory/video being loaded into memory).

What I mean when I say `Transitions` aren't guaranteed to be in-order is that `Transitions` isn't documented as requiring that each index is in timestep order right now. We could just add that to the docstring if this is something we want to enforce without the `in_order` flag.

**Comment by shwang** [comment]
> > One idea is to save `List[Trajectory]` as a `npz`. `npz` supports Dict (we could make each list index an integer key in the dict form).
> > ```python
> > {
> > 1: dict(obs=..., acts=..., infos=...),
> > 2: ...,
> > 
> > }
> > ```
> 
> This would work but is less efficient than saving `Transitions`. There's a lot of overhead in each object you store.
> 
> And it seems nice to be able to save and load `Transitions` too.

I think that we should use `.npz` as our save format because numpy can automatically compress arrays for us. (Of course, we could compress ourselves too.)

When you say it's less efficient than saving `Transitions` do you mean that there's an extra layer of overhead involved with the dictionary format (agreed.)?

In other ways this solution is more efficient to use as the canonical rollout format because `List[Trajectory(WithRew)]` contains the minimum possible rollout information to construct all the different types of `Transitions`. If the observation space is big (color images) then the `TransitionsWithRews` type will be wasteful because it duplicates every image.

I think having the dictionary save format might actually be favorable over directly pickling a dataclass the dictionary save format will be independent from any changes we make to the dataclasses, so it can be loaded and processed if we decide to change `Trajectory` around later. If we decide to use it this way, maybe it would make sense to add a `version` integer or something for future compatibility.

**Comment by AdamGleave** [comment]
> I think that we should use `.npz` as our save format because numpy can automatically compress arrays for us. (Of course, we could compress ourselves too.)

Sorry I was unclear, I agree `npz` is a good format.

 
> When you say it's less efficient than saving `Transitions` do you mean that there's an extra layer of overhead involved with the dictionary format (agreed.)?

Yeah that's what I meant.

> 
> In other ways this solution is more efficient to use disk-storage-wise as the canonical rollout format because `List[Trajectory(WithRew)]` contains the minimum possible rollout information to construct all the different types of `Transitions`. If the observation space is big (color images) then the `TransitionsWithRews` type will be wasteful because it duplicates every image.

Good point re: duplicated observations. I guess the most efficient method would be to save an array of observations, actions and dones -- with the observations including the first and last observation of each episode. Then this can be reconstituted into either a `Trajectory` or a `Transition`. This is how the GAIL [Dataset](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/gail/dataset/dataset.py) works I think.

This does lose some generality, though: we could no longer represent arbitrary `Transition` objects in the save format (e.g. those out of order).

> I think having the dictionary save format might actually be favorable over directly pickling a dataclass because the dictionary save format will be independent from any changes we make to the dataclasses, so it can be loaded and processed if we decide to change `Trajectory` around later. If we decide to use it this way, maybe it would make sense to add a `version` integer or something for future compatibility.

Oh this is way better than directly pickling it, I did not ever mean to suggest we should keep pickling it.

**Comment by AdamGleave** [comment]
I think given the above discussion, my vote would be to continue having `Trajectory` or `TrajectoryWithRew` be the canonical format we serialize/deserialize in, but internally:
  - Concatenate all the arrays across episodes, introducing `dones` at boundaries.
  - Save in `npz` format `dict(obs=flattened_obs,act=flattened_act,dones=dones,infos=flattened_infos)`
  - Do the inverse of this when deserializing.
This seems minimal disk storage.

**Comment by AdamGleave** [comment]
We've recently had issues with pickled trajectories not being able to be deserialized in newer versions of Python, which bumps up the priority for this; I'm adding this to the v1.0 milestone.
