### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#19]
Consistent use of Google style docstrings. This is the best [summary](https://gist.github.com/redlotus/3bc387c2591e3e908c9b63b97b11d24e) I've seen; also see [Napolean](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/sphinxcontrib.napoleon.html#sphinxcontrib.napoleon.docstring.GoogleDocstring) and [official style guide](http://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings). Main violations I see in the codebase right now are:
  - Starts with a paragraph. Should be first line summary, new line, then additional info.
  - Using `Params` rather than `Args`, not indenting things.
  - Being imperative: it should be descriptive. So, `Computes fizzbuzz`, not `Compute fizzbuzz. 
  - Having first line just be `"""`. Should be followed with text.

We're also including types in the documentation, which is not usual Google style, but I think is good practice. I suggest we do it in the form:
  `n: (int) a natural number`
not:
  `n (int): a natural number`
so that automatic documentation generation tools like `Sphinx` will be happy.

We should also make sure each module has at least a one-sentence docstring. I'd also suggest doing this for all methods, there are a few without. I don't think it's necessarily worth writing copious documentation for each function at this stage, though: many are self-explanatory.

**Comment by shwang** [comment]
What do you think about make 2-space indentation everywhere including docstring for consistency?

For what it's worth, TF does 2-space [indentation everywhere](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/composite_tensor.py#L147).

**Comment by AdamGleave** [comment]
That's the style I believe I followed in reward_net (except for line
continuations which I made 4 spaces for legibility). Think it's a good idea.

**Comment by AdamGleave** [comment]
Also it seems I'm wrong about where the types should go: both the example I linked and the Napolean definition have types like `n (int): a natural number`. I don't see this actually specified anywhere in the Google Style Guide. Think I got confused as Stable Baselines seems to use the other convention. I'm not sure it's worth changing back though...
