### ISSUE TITLE
Basic docs / quickstart tutorial

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#190]
We have a Sphinx build and I've set up [readthedocs](https://imitation.readthedocs.io/), but right now our documentation is very unstructured. We actually have pretty good docstrings on individual classes, but no intro guide, or other structure that would help new users.

Not that high priority: I think it's more important to focus on making the algorithms solid and possibly doing some refactoring. But once we have that a small tutorial would make a big difference to adoption.

**Comment by araffin** [comment]
as discussed with @Miffyli , I would be for integrating some doc (presentation of the lib and example) directly in SB3 doc (as it is done for the zoo).
I have a plan to do the same for offline algos implemented in https://github.com/takuseno/d3rlpy (see issue https://github.com/takuseno/d3rlpy/issues/5).
Both repos are nice extension to SB3.

**Comment by AdamGleave** [comment]
Sounds good -- let us know if we can help with this, by e.g. providing examples of `imitation`

**Comment by araffin** [comment]
>Sounds good -- let us know if we can help with this, by e.g. providing examples of imitation

Would be good if someone from your team could to a PR to add a page with presentation and examples, as I already have other doc to write ;)
(see https://github.com/DLR-RM/stable-baselines3/issues/166)

**Comment by AdamGleave** [comment]
@shwang do you have the bandwidth to do this?

**Comment by Miffyli** [comment]
A suggestion: Add quick example close to top in README to demonstrate the ease of use (in minimal case) outside the premade script runs. I found the BC implementation here very convenient to use with my experiments!

**Comment by shwang** [comment]
I wrote up a quickstart blurb over here as per @Miffyli's suggestion.

https://gist.github.com/shwang/aba1711ffec8a83da4a315ab10c6cd62

I'm thinking that with some editing, this could comprise half of the SB3 docs page alongside a written description of the project?

**Comment by araffin** [comment]
>I'm thinking that with some editing, this could comprise half of the SB3 docs page alongside a written description of the project?

yes, look good, thanks =)
I would also add a one sentence description of each algorithm implemented and a link to the paper.
Also, once the imitation doc is online, we will link to it (so people can take a look at the available parameters).

**Comment by shwang** [comment]
Imitation docs are actually [already online](https://imitation.readthedocs.io/en/latest/imitation.algorithms.html#module-imitation.algorithms.adversarial) in a rudimentary form, but the default Sphinx layout makes it super hard to read.

I'm thinking it's best to just link to the GitHub page for now.

**Comment by araffin** [comment]
>but the default Sphinx layout makes it super hard to read.

You should consider using the read the doc them (as done in SB2/SB3).

**Comment by AdamGleave** [comment]
> You should consider using the read the doc them (as done in SB2/SB3).

I think the main problem is we haven't added anything other than auto-generated docs, so it's quite terse.

**Comment by shwang** [comment]
Haha it's not just terse, but unreadable:

![image](https://user-images.githubusercontent.com/1750835/96960786-17287f00-14b8-11eb-91ef-b86f74d16e1a.png)

I'm surprised that `AIRL.__init__` doesn't get to make an appearance on the Sphinx render. There's probably some setting we can fiddle with to make that appear.

**Comment by AdamGleave** [comment]
> Haha it's not just terse, but unreadable:
> 
> ![image](https://user-images.githubusercontent.com/1750835/96960786-17287f00-14b8-11eb-91ef-b86f74d16e1a.png)
> 
> I'm surprised that `AIRL.__init__`'s docstring doesn't get to make an appearance on the Sphinx render. There's probably some setting we can fiddle with to make that appear.

I've added:
```python
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "special-members": "__init__",
    "show-inheritance": True,
}
```
to our `docs/conf.py` in your PR https://github.com/HumanCompatibleAI/imitation/pull/238 (for lack of a better place). This is including `__init__` now. https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method suggests you can also set `autoclass_content = 'both'` to concatenate `__init__` to the class docstring, but I think we want them to be distinguished.

I've also switched our theme to RTD which is nicer.

But we still need to actually structure the documentation and add some discussion that's not in the docstrings before this is really approachable to new users.

**Comment by shwang** [comment]
Done a month or two ago.

**Comment by mstkocyigit** [comment]
please add a tutorial in YouTube.
