### ISSUE TITLE
PPO2 producing new Tensorboard events files with every call to PPO2.learn()

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#192]
Related to https://github.com/hill-a/stable-baselines/issues/855.

To reproduce this problem:

`python -m imitation.scripts.train_adversarial with init_tensorboard=True`.

I get a growing list of files like:

```
├── sacred -> ../../home/steven/PycharmProjects/imitation/output/sacred/train/295
├── sb_tb
│   └── PPO2_1
│       ├── events.out.tfevents.1589433242.spinach
│       ├── events.out.tfevents.1589433245.spinach
│       ├── events.out.tfevents.1589433248.spinach
│       ├── events.out.tfevents.1589433250.spinach
│       ├── events.out.tfevents.1589433253.spinach
│       ├── events.out.tfevents.1589433255.spinach
│       ├── events.out.tfevents.1589433257.spinach
│       ├── events.out.tfevents.1589433260.spinach
│       ├── events.out.tfevents.1589433262.spinach
│       └── events.out.tfevents.1589433265.spinach
└── tb
    └── events.out.tfevents.1589433245.spinach
```

Leads eventually to "too many files open by this process" error and ends the run. Also makes the Tensorboard plots take a very long time to load because there are so many files.

I believe that with every call to `.learn()` in this case PPO2 is initializing a new `tf...FileWriter` and `tf...EventWriter`, which automatically creates a new file.

**Comment by Jiankai-Sun** [comment]
Same problem. @AdamGleave

**Comment by shwang** [comment]
@Jiankai-Sun Looking at the `new_tb_log = False` thing today, maybe that will work.

**Comment by shwang** [comment]
Resolving this issue would be a trivial way to track learned episode rewards over time, as PPO2 tracks this when `init_tensorboard=True`.

**Comment by AdamGleave** [comment]
I think this has been fixed by setting a custom logger; SB3 will no longer attempt to create a logger at all. Running `python -m imitation.scripts.train_adversarial with half_cheetah_airl`, I only observe one events file. If this problem reoccurs feel free to re-open with a MWE.
