### ISSUE TITLE
Basic script usage (the example in README.md) fails

### ISSUE THREAD

**Issue by ejmichaud** [HumanCompatibleAI/imitation#215]
I am in the `port_clones_to_pytorch` branch: #208 
The following commands, as listed in the README are failing for me:
```
# Train PPO2 agent on cartpole and collect expert demonstrations
python -m imitation.scripts.expert_demos with cartpole
# Train AIRL on from demonstrations
python -m imitation.scripts.train_adversarial with cartpole airl
```
I have followed the installation instructions exactly and am running on `Ubuntu 18.04.4 LTS`. 
The first command (`expert demos`) displays the following error after training the policy:
```
INFO - root - Rollout stats: {'n_traj': 14, 'return_min': 203.0, 'return_mean': 322.64285714285717, 'return_std': 115.8352322068211, 'return_max': 500.0, 'len_min': 203, 'len_mean': 322.64285714285717, 'len_std': 115.8352322068211, 'len_max': 500}
INFO - root - Dumped demonstrations to output/expert_demos/CartPole-v1/20200722_155156_022b0f/rollouts/final.pkl.
INFO - root - Saved policy to output/expert_demos/CartPole-v1/20200722_155156_022b0f/policies/final
INFO - expert_demos - Result: {'n_traj': 57, 'return_min': 7.388836879311779, 'return_mean': 15.001208959872894, 'return_std': 3.078998671602082, 'return_max': 17.673824873098567, 'len_min': 215, 'len_mean': 441.29824561403507, 'len_std': 91.40174763431135, 'len_max': 500, 'monitor_return_min': 215.0, 'monitor_return_mean': 441.29824561403507, 'monitor_return_std': 91.40174763431135, 'monitor_return_max': 500.0}
INFO - expert_demos - Completed after 0:02:01
ERROR - expert_demos - Failed after 0:02:02!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/eric/Code/miniconda3/envs/imitation/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/eric/Code/miniconda3/envs/imitation/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/home/eric/Code/miniconda3/envs/imitation/lib/python3.7/subprocess.py", line 1645, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['tee', '-a', '/tmp/tmp7r4n8frp']' timed out after 1 seconds
```
Then when I execute the second command (`train_adversarial`), again from the repository root directory, I get:
```
WARNING - root - Added new config entry: "__doc__"
WARNING - root - Added new config entry: "discrim_net_kwargs.gail.scale"
INFO - train_adversarial - Running command 'train'
INFO - train_adversarial - Started run with ID "4"
ERROR - train_adversarial - Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/eric/Code/chai/imitation/src/imitation/scripts/train_adversarial.py", line 120, in train
    assert os.path.exists(rollout_path)
AssertionError
```
I'd be happy to provide more info. Looks to be an issue with how the scripts are saving/looking for files, and not something deeper with the `imitation` algorithms.

**Comment by shwang** [comment]
Hey Eric, thanks for the traces.

I'm getting the same Sacred Tee error when running expert_demos on my own computer with the new branch.

In #194 we made sure this doesn't happen in the testing suite by forcing Sacred to use `--capture sys` mode instead. There's also a more permanent fix waiting at https://github.com/IDSIA/sacred/pull/740 to be reviewed by the Sacred maintainers.

**Comment by shwang** [comment]
As for the `rollout_path` assertion error, that's a not very descriptive error that raised when the GAIL/AIRL doesn't actually have any rollouts to load from disk.

Normally you can download them via `experiments/download_experts.sh` but that directory is filled with TF1 experts right now, not pytorch SB3 experts.

**Comment by AdamGleave** [comment]
We should definitely make the `rollout_path` error more informative. We should really avoid using `assert` for anything user facing: it's meant to be an internal check on programming logic only.

For completeness, I think @ejmichaud would need to run `python -m imitation.scripts.train_adversarial with cartpole airl rollout_path=output/expert_demos/CartPole-v1/20200722_155156_022b0f/rollouts/final.pkl` for it to work?

**Comment by xjtueryx** [comment]
I'm getting the same error when running expert_demos. How to solve it?
Thanks!

**Comment by shwang** [comment]
The error message in the issue was made more informative by #228, and the example script that caused the error was replaced entirely with one checked by CI in #190 today.

Note that we still can't run the command `python -m imitation.scripts.expert_demos with cartpole` out-of-the -box because we don't have #230 yet.

**Comment by xiaofeng-fan** [comment]
I installed the latest release but am still unable to run the examples in README. Any hints?
Running `python -m imitation.scripts.expert_demos with fast cartpole log_dir=quickstart/rl/` gave
```
/home/flint/anaconda3/envs/imitation/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
INFO - expert_demos - Running command 'rollouts_and_policy'
INFO - expert_demos - Started run with ID "5"
ERROR - expert_demos - Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/mnt/Data_SSD/projects/6244/imitation/src/imitation/scripts/expert_demos.py", line 103, in rollouts_and_policy
    sacred_util.build_sacred_symlink(log_dir, _run)
  File "/mnt/Data_SSD/projects/6244/imitation/src/imitation/util/sacred.py", line 80, in build_sacred_symlink
    os.symlink(target_path, symlink_path, target_is_directory=True)
FileExistsError: [Errno 17] File exists: '../../output/sacred/expert_demos/5' -> 'quickstart/rl/sacred'

```

**Comment by shwang** [comment]
@xiaofeng-fan: Thanks for reporting this.

That's an uninformative failure that pops up right now when you train a second time on the same `log_dir` twice (Don't believe that this will occur the first time you run the quickstart script.).

Before this is fixed, you should be able to bypass this error either by deleting `quickstart/rl` or by changing the value of `log_dir=...`.

**Comment by xiaofeng-fan** [comment]
@shwang Thanks for the reply. The fix indeed solved the problem for now.
