### ISSUE TITLE
Final TF1 release

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#217]
Make a final PyPI release for TF1 representing the final commit before SB3 port.

Before this can happen, need to wait for the next release of SB2, as we are currently relying on a commit in the master branch that isn't in the latest SB2 PyPI release:

https://github.com/HumanCompatibleAI/imitation/blob/202b50e9d4373b4cc9bfe6a14e1208fd9ba63dc3/setup.py#L55-L58

**Comment by AdamGleave** [comment]
The next SB2 release might not happen for a bit. We could:
    - Make a branch ready for the TF1 release, but don't release it until SB2 release happens. Then we can just release e.g. a `0.1.1` release, but continue with PyTorch development as `0.2` and afterwards.
    - If we want a release earlier (e.g. for use in our own projects), monkey patch `CloudPickleWrapper` (it's just one line change after all).

**Comment by araffin** [comment]
@AdamGleave The SB2 release can be almost done, I wanted that to be fixed first: https://github.com/hill-a/stable-baselines/issues/906

**Comment by AdamGleave** [comment]
> @AdamGleave The SB2 release can be almost done, I wanted that to be fixed first: [hill-a/stable-baselines#906](https://github.com/hill-a/stable-baselines/issues/906)

Great, looking forward to it!
