### ISSUE TITLE
Belated code review

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#22]
Meta issue I will be updating with points I notice as I read through the code, that seem too small to be worth creating their own issue about.

- [x] Consider using stable_baselines `observation_input` to build placeholders with preprocessed output. This will let us work smoothly with a variety of observation and action spaces.
- [x] Use `tf.layers.flatten` instead of `util.flat` (which I think can be deleted). I believe this would also let us get rid of passing the shape around explicitly with the tensor (since `tf.layers.flatten` extracts it automatically).
- [ ] In `RewardModel`, pass in `observation_space` and `action_space` rather than a `gym.Env`, since we do not seem to ever need other properties of the `gym.Env`.

**Comment by shwang** [comment]
- [ ] Reduce use of `tf.identity(..., name=...)` by adding a name param to `apply_ff`.

**Comment by shwang** [comment]
>  In RewardModel, pass in observation_space and action_space rather than a gym.Env, since we do not seem to ever need other properties of the gym.Env.

I'm confused by this because I don't see any subclass of `RewardModel` or `RewardModel` itself requiring `env` in `imitation/tabular_irl.py`

**Comment by AdamGleave** [comment]
> > In RewardModel, pass in observation_space and action_space rather than a gym.Env, since we do not seem to ever need other properties of the gym.Env.
> 
> I'm confused by this because I don't see any subclass of `RewardModel` or `RewardModel` itself requiring `env` in `imitation/tabular_irl.py`

Sorry I meant `RewardNet`, in `imitation/reward_net.py`. (The equivalent class in my codebase is `RewardModel`, got them mixed up.)
