### ISSUE TITLE
Make logger live in imitation rather than stable_baselines3?

### ISSUE THREAD

**Issue by qxcv** [HumanCompatibleAI/imitation#222]
At the moment we monkey-patch the SB logger with our own hierarchical logger so that both imitation & SB algorithms can access the same logger. This looks a bit weird in downstream code: the actual logger object gets imported from SB, even though the logger _implementation_ is in `imitation`. Stylistically, it might be clearer if we added a proxy for the SB logger to imitation. That way both us and our users could import the logger from the `imitation` package instead of the `stable_baselines3` package. This wouldn't cause any functional change, but would make it more clear where the logger is actually implemented.

(thanks to @decodyng for this suggestion)

**Comment by AdamGleave** [comment]
I agree this seems cleaner.

**Comment by AdamGleave** [comment]
Fixed in https://github.com/HumanCompatibleAI/imitation/pull/328
