### ISSUE TITLE
AdversarialTrainer: Is n_gen_batch_size off by factor of n_vec?

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#234]
The definition of the `AdversarialTrainer.gen_batch_size` property implies that `n_steps == gen_batch_size`. Is this wrong? I'm think that this really should be `n_steps * n_vec == gen_batch_size` IIRC.

**Comment by AdamGleave** [comment]
Yeah this seems correct to me, nice catch.
