### ISSUE TITLE
Hard-to-read piped output in Adversarial and elsewhere because of tqdm progress bars.

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#235]
https://github.com/HumanCompatibleAI/imitation/pull/231#discussion_r504399263

**Comment by shwang** [comment]
I believe that this is resolved for BC somewhere in our `image-env-changes` dev branch that we are using for another project. Will need to break that branch into changes sometime eventually, but I don't have bandwidth for that currently.

**Comment by AdamGleave** [comment]
This seems like a fairly minor issue so I'm closing for now, though would be happy to see a PR for this in the future.

**Comment by shwang** [comment]
BTW there’s already a progress visible argument added to BC
