### ISSUE TITLE
installation, Jaxlib problem

### ISSUE THREAD

**Issue by SNYAHS** [HumanCompatibleAI/imitation#240]
I got this error while trying to install !
ERROR: Could not find a version that satisfies the requirement jaxlib~=0.1.47 (from imitation==0.1.1a0) (from versions: none)
ERROR: No matching distribution found for jaxlib~=0.1.47 (from imitation==0.1.1a0)

**Comment by AdamGleave** [comment]
Does `pip install jaxlib` work for you at all?

We might need to relax the version requirements in `setup.py` (@qxcv is there any particular range we need?), but OTOH seems we're allowing anything more recent than 0.1.47 that is still in 0.1.x, which should include the latest jaxlib release.

**Comment by qxcv** [comment]
I don't think so. I'd guess we can just upgrade jax to the latest version. If the test suite fails we can roll back.

**Comment by SNYAHS** [comment]
Seems a prob specific to Windows
google/jax#507

**Comment by AdamGleave** [comment]
I think we only use `jaxlib` for BC and DAGGER -- not for AIRL or GAIL at least -- so as a workaround you could just delete that line, and most algorithms will probably still work.

Closing since we can't fix this without upstream adding support.

**Comment by aaronsnoswell** [comment]
Ouch! +1 - came here because I couldn't get the readme installation instructions to work - turns out Jax isn't supported on windows :(

Maybe we can update the readme to reflect this limitation?
