### ISSUE TITLE
Wrong Policy baseclass 

### ISSUE THREAD

**Issue by stheid** [HumanCompatibleAI/imitation#250]
This should actually be `ActorCriticPolicy`
https://github.com/HumanCompatibleAI/imitation/blob/7c2882697b92b1b93cc32b36d4d4bce8916cf880/src/imitation/algorithms/bc.py#L155

as there are later functions called, that are not implemented in the `BasePolicy`
https://github.com/HumanCompatibleAI/imitation/blob/7c2882697b92b1b93cc32b36d4d4bce8916cf880/src/imitation/algorithms/bc.py#L264

**Comment by shwang** [comment]
Thanks for the heads-up. We discovered this discrepancy around the same time you did and made this change in #251.

**Comment by AdamGleave** [comment]
Closing then, feel free to re-open if this is still an issue.

**Comment by AdamGleave** [comment]
Oh, I see we haven't actually merged https://github.com/HumanCompatibleAI/imitation/pull/251 Maybe we should split that change out into a separate PR if https://github.com/HumanCompatibleAI/imitation/pull/251 is still going to take a while? It seems like an easy fix to make.

**Comment by AdamGleave** [comment]
Fixed now (for a long time), closing
