### ISSUE TITLE
'device' in kwargs in bc causes error 

### ISSUE THREAD

**Issue by JeongHyunho** [HumanCompatibleAI/imitation#254]
ActorCriticPolicy which is the default policy doesn't have 'device' as input
 
https://github.com/HumanCompatibleAI/imitation/blob/7c2882697b92b1b93cc32b36d4d4bce8916cf880/src/imitation/algorithms/bc.py#L192-L197

https://github.com/HumanCompatibleAI/imitation/blob/7c2882697b92b1b93cc32b36d4d4bce8916cf880/src/imitation/algorithms/bc.py#L201-L202

https://github.com/DLR-RM/stable-baselines3/blob/e747e7e2b3f92a6650a7d69fd839544db4c5ffba/stable_baselines3/common/policies.py#L364-L383

**Comment by AdamGleave** [comment]
Thanks for the report! Looks like a bug.

@qxcv @scottemmons Is there a reason we use `self.device` twice -- once as a policy keyword argument and once via `.to`? Can we drop it from the `kwargs` and just use `to`, or does `to` fail to relocate some objects with certain policies?

**Comment by qxcv** [comment]
Previously it did have a `device` kwarg, it was just removed in https://github.com/DLR-RM/stable-baselines3/commit/42ef6d4677511d5d35d4f911447ce37739660f90. It can be removed from our code now, so long as we have the latest SB3 pinned as a dep.

**Comment by AdamGleave** [comment]
Ah, gotcha. Seems like we currently depend on an old version of SB3 (0.8.0), but it should be fine to update this. v1 will be coming out soon anyway.

Are you OK making a PR for this? Otherwise I can probably do it tomorrow.

**Comment by qxcv** [comment]
I've made #255, but it seems like CircleCI is being weird. Added some comments to the PR explaining the issue.
