### ISSUE TITLE
Improving visualizations for `scripts/train.py`

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#26]
In `plot_and_train`, GAIL shows "Learned Reward" performance right now, even though GAIL doesn't actually learn a reward.
![image](https://user-images.githubusercontent.com/1750835/60478288-07d45100-9c37-11e9-990a-71754694cda0.png)

This is because we are shoehorning GAIL's `DiscrimNetGAIL` into an `ABC`  that requires a `build_policy_test_reward`, and having `build_policy_test_reward` return the negative classification cross entropy as test reward.
https://github.com/HumanCompatibleAI/imitation/blob/master/imitation/discrim_net.py#L140

I should change the title of this plot in the GAIL case, it seems like it can still be useful. Also I should document `DiscimNetGAIL` so it is clear why we are returning something rather than `nan` for the test reward.

- [x] Titles and legend labels that makes it more obvious what the plots are doing.
- [x] Show training reward for AIRL.
- [ ] Somehow make it clear that GAIL's "Learned Reward" AKA `build_policy_test_reward` is cross entropy in the plots rather than an actual reward.

**Comment by AdamGleave** [comment]
Reporting GAIL discriminator confusion is useful, we should definitely keep this plot, but changing the title would be good :)

**Comment by shwang** [comment]
stale / these plots don't exist any more
