### ISSUE TITLE
numpy.float128 not supported on Windows

### ISSUE THREAD

**Issue by Jiloc** [HumanCompatibleAI/imitation#268]
Hi, 
first of all thanks for the amazing work.

I am working on windows and [this line](https://github.com/HumanCompatibleAI/imitation/blob/9ddd6fa9a0a735243ffaa536cb31edc88250bd98/src/imitation/data/types.py#L75) throws

> AttributeError: module 'numpy' has no attribute 'float128'

when I try to generate rollouts for GAIL/AIRL.

I just removed it to make it work on my end, but it would be nice to have this project working as-is on windows too.

**Comment by AdamGleave** [comment]
Thanks for opening the issue! We don't officially support Windows, but this seems like a sad reason to fail (and I expect it could drop up on Linux depending on hardware platform too).

I think we can replace this line with `isisinstance(rews.dtype.type, np.floating)` -- WDYT @shwang?
