### ISSUE TITLE
Logging in Adversarial Trainer for both Policy and Discriminator

### ISSUE THREAD

**Issue by amy12xx** [HumanCompatibleAI/imitation#269]
I'm trying to run the quickstart example: https://github.com/HumanCompatibleAI/imitation/blob/master/examples/quickstart.py

I would like both PPO training and GAIL training to be logged on tensorboard. What I'm seeing is when I execute the training for GAIL, PPO tensorboard logs do not get generated.

logger.configure(tempdir_path / "GAIL/")
gail_trainer = adversarial.GAIL(
    venv,
    expert_data=transitions,
    expert_batch_size=32,
    gen_algo=sb3.PPO("MlpPolicy", venv, verbose=1, n_steps=1024),
)
gail_trainer.train(total_timesteps=2048)

If I try to pass the tensorboard_log parameter to PPO, I get an error that "Shouldn't call stable_baselines3.logger.configure once imitation.logger.configure() has been called". If I remove the logger.configure line above, I get an assertion that I have to instantiate. 
        assert (
            logger.is_configured()
        ), "Requires call to imitation.util.logger.configure"

I can't pass the logger object either to Stable Baselines 3, since it seems to create one during _setup_learn() in BaseAlgorithm class.

Any ideas on what a good workaround is to get logging (including tensorboard logs) for both done?

**Comment by AdamGleave** [comment]
This should work with new logger, feel free to re-open with MWE if it's still an issue.
