### ISSUE TITLE
Question: How to use the trained GAIL?

### ISSUE THREAD

**Issue by cristinagatt** [HumanCompatibleAI/imitation#272]
Hi, 
Thank you for providing such a clean implementation of IL algorithms.  I am quite new to the Imitation Library and Stable Baselines 3. I followed the examples available on the repository but I can't seem to figure out how to use the trained GAIL to predict next actions after it is trained. 

What is the equivalent of the 'model.predict()' in SB3 for this library? Is it possible to provide a simple example to illustrate this? 
Thank you.

**Comment by AdamGleave** [comment]
GAIL & AIRL train an SB3 policy under the hood. If `adv_trainer` is an instance of `AdversarialTrainer` you can access the SB3 policy via `adv_trainer.gen_algo`, so you could do `adv_trainer.gen_algo.predict(...)`.

@shwang maybe we should add an example of this to https://github.com/HumanCompatibleAI/imitation/blob/master/examples/quickstart.py ?
