### ISSUE TITLE
Slowdown due to PyTorch multithreading contention when running experiments in parallel

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#274]
If I run 5 RL training jobs in parallel via multiprocessing (or anything Pytorch in parallel) I get massive throttling:

![image](https://user-images.githubusercontent.com/1750835/113221214-72198b80-9239-11eb-9863-d305194c592a.png)

This is because every in every process, Pytorch by default creates a thread for every core (or something similar to that), which leads to massive multithreading contention.

A quick fix to this problem is calling
```
import torch as th
th.set_num_threads(2)
th.set_num_interop_threads(2)
```
at the start of training, as we already do automatically in our pytest settings: https://github.com/HumanCompatibleAI/imitation/blob/e7e87b2e7e791d5d0c37aaa0ab813d333fc6e6fb/tests/conftest.py#L10-L27 .

Should we considering calling this function at the start of every `imitation.scripts.*`? Or even injecting this call into `imitation.__init__`? (The second choice seems too sneaky).

**Comment by shwang** [comment]
This comment seems to suggest setting an environment variable `OMP_NUM_THREADS` to regulate the number of threads automatically spawned by PyTorch: https://github.com/pytorch/pytorch/issues/3146#issuecomment-624397273

e.g. `OMP_NUM_THREADS=1` should automatically achieve what `conftest.py` is doing with single-threading above.

**Comment by AdamGleave** [comment]
How much speedup do we actually get from multiple threads (when just running one process)? We might want to set it to a smaller value by default. Right now it's a bit of a footgun if running even a small number of instances in parallel grinds to a halt. I'd suggest at least prominently documenting the need to set `OMP_NUM_THREADS`.

**Comment by shwang** [comment]
At a glance it looks like `export OMP_NUM_THREADS=1` has slowed down my experiments by a factor of ~2 relative to using
```
import torch as th
th.set_num_threads(2)
th.set_num_interop_threads(2)
```

on my machine. Maybe I could run an actual benchmark later.

**Comment by shwang** [comment]
This problem has been resolved for our experiment scripts by an export statement `export OMP_NUM_THREADS=12 in `common.env` in #319 .

Would still be nice to add prominent documentation, or maybe a warning if `OMP_NUM_THREADS` is not detected

**Comment by AdamGleave** [comment]
This isn't a bug in `imitation` per-se. Documentation would be nice -- I don't think it's worth adding it just for this, but if we ever have a section on parallel experiments, would be a good thing to include. For now, closing.
