### ISSUE TITLE
GAIL - Expert batch size - Variable Size

### ISSUE THREAD

**Issue by cristinagatt** [HumanCompatibleAI/imitation#280]
Hi,

I'm using GAIL and the parameter 'expert_batch_size' is set as required. From the relevant documentation, if I understood correctly, this is the number of steps an expert takes to achieve a goal.  However, in my use case, different experts take a different number of steps (actions, observations) to achieve the same goal. Therefore, if I set the 'expert_batch_size' to x, one expert could take x-10 steps while the other could take x+10 steps to get to the goal, which will disrupt training.  Did I understand this parameter correctly? If so, is there a way to mitigate this issue please?

Thank you :)

**Comment by AdamGleave** [comment]
Batch size is how many expert timesteps to train on. Can be smaller or larger than time taken to reach the goal. Hope that helps clarify things. Best of luck!
