### ISSUE TITLE
"got an unexpected keyword argument 'device'" when initializing BC class

### ISSUE THREAD

**Issue by sph001** [HumanCompatibleAI/imitation#282]
I'm running into a `TypeError: __init__() got an unexpected keyword argument 'device'` error when attempting to use Behavior cloning as described in the example, and I cant seem to narrow down what the issue is as the device kwarg that its complaining about is from the BC class.

line which causes the issue:
```python
bc_trainer = bc.BC(env.observation_space, env.action_space, expert_data=transitions)
```
trace
```python
Traceback (most recent call last):
  File "/home/user/behaviorcloning.py", line 45, in <module>
    bc_trainer = bc.BC(env.observation_space, env.action_space, expert_data=transitions)
  File "/home/user/venv/lib/python3.7/site-packages/imitation/algorithms/bc.py", line 116, in __init__
    self.policy = self.policy_class(**self.policy_kwargs).to(
  File "/home/user/venv/lib/python3.7/site-packages/imitation/policies/base.py", line 66, in __init__
    super().__init__(*args, **kwargs, net_arch=[32, 32])
TypeError: __init__() got an unexpected keyword argument 'device'
```

**Comment by Mathieu-Geisert** [comment]
I got the same issue.

Stable_baselines3 and imitation were installing using ubuntu 20.04, python 3.7, pip 21.1.3, stable_baselines3 1.1.0, imitation 0.2.0.

It can be solved manually by removing "device=self.device" in bc.py at line 111.

best,
Mathieu

**Comment by AdamGleave** [comment]
Can't replicate this error, assuming it was fixed a while back (may have been some version incompatibility since AFAICT we never saw this breakage in unit tests). If you still experience this then feel free to reopen (ideally with a MWE).

**Comment by pmRed** [comment]
I was experiencing this issue too. Found that imitation provided through pypi is inconsistent with the version tagged as 0.2.0 on the git repository. 

On [pypi](https://pypi.org/project/imitation/0.2.0/) bc.py - line 107-onwards is
```python
         self.policy_kwargs = dict(
            observation_space=self.observation_space,
            action_space=self.action_space,
            lr_schedule=ConstantLRSchedule(),
            device=self.device,
        )
```
[Repo for v0.2.0](https://github.com/HumanCompatibleAI/imitation/blob/e7e87b2e7e791d5d0c37aaa0ab813d333fc6e6fb/src/imitation/algorithms/bc.py#L192
) has:
```python
        self.policy_kwargs = dict(
            observation_space=self.observation_space,
            action_space=self.action_space,
            lr_schedule=ConstantLRSchedule(),
        )
```

Quick Fix: Install directly from the repo.

**Comment by AdamGleave** [comment]
Sorry about this issue, we plan to put out a new release soon with this bugfix + many new features. Currently waiting on the new implementation of DRLHP to stabilize.
