### ISSUE TITLE
Question: Why the  GAIL generator  does not access the discriminator?

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [HumanCompatibleAI/imitation#289]
Hi,

the authors of GAIL say they use TRPO with cost function log(Disc(s,a)) to update the generator/policy parameters. In your implementation you use PPO for the generator, but you don't use the discriminator to obtain the [loss](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/ppo/ppo.py#L241) . How is this valid? 
Thank you!

Best:
Stoyan

**Comment by AdamGleave** [comment]
We use the discriminator to generate the reward, and the loss depends on the reward.
