### ISSUE TITLE
setup.py issues

### ISSUE THREAD

**Issue by qxcv** [HumanCompatibleAI/imitation#29]
A couple of minor issues with setup.py:

- It seems to duplicate the dependencies in `requirements.txt` and `requirements-dev.txt`. Ideally we could delete one or both of the `requirements.txt` files & move the deps into `setup.py`.
- `pip install -e .[cpu]` installs both `tensorflow` and `tensorflow-gpu` on my machine. That's probably because `stable-baselines` has a [different (weird) check](https://github.com/hill-a/stable-baselines/blob/master/setup.py#L12-L34) for whether or not to install GPU tensorflow (basically: if TF is not installed already, then it installs GPU TensorFlow iff `nvidia-smi` is on the PATH). Not sure if that's worth fixing on their end.
- Dependencies aren't pinned to specific version ranges. That's going to screw things up eventually, particularly if someone installs from `requirements.txt` & ends up with a `master` release of `stable-baselines` (due to `git+git://github.com/hill-a/stable-baselines.git#egg=stable-baselines` dep).

**Comment by AdamGleave** [comment]
:+1: on not duplicating the requirements.

I have mixed feelings about pinning version ranges. It does make things more reliable. However, it makes the default being staying on old versions. So we'd need to make sure we periodically update things, whereas things breaking is a natural reminder ;) We should use releases rather than `master` versions where possible though.

**Comment by qxcv** [comment]
What's the main reason you want to regularly update the dependencies, though? For some projects I think that's 100% necessary for security reasons, but here that's not such a big deal.

**Comment by AdamGleave** [comment]
I'd agree if `imitation` was a stand-alone app, but it's also being used in third-party code. So it'd be good for us to support a range of versions, including the latest one. Users may not be able to match our exact version requirements if they use other libraries with different requirements, or for policy reasons (e.g. right now I'm subject to Google's [one version rule](https://opensource.google.com/docs/thirdparty/oneversion/).)

**Comment by qxcv** [comment]
Ahh okay, I hadn't thought of that, but I agree it's a desirable property for this project to have.

**Comment by AdamGleave** [comment]
Can we close this now that #49 is merged?

**Comment by qxcv** [comment]
The GPU TF install issue still exists, but I don't think there's a clean way to solve it, so we may as well close this issue.
