### ISSUE TITLE
Make `awscli` and `cloudpickle` optional dependencies

### ISSUE THREAD

**Issue by lassepe** [HumanCompatibleAI/imitation#302]
Currently, this package pulls in a few dependencies that are not used by the main library code. Since `awscli` and `cloudpickle` are two rather heavy dependencies that are only used in the experiments, I was wondering whether they could be made optional since they cause some [issues downstream](https://github.com/python-poetry/poetry/issues/2094#issuecomment-889882745) as well.

**Comment by AdamGleave** [comment]
This seems like a reasonable suggestion. 

@shwang can you recall why we need these dependencies? I don't see any usage of `cloudpickle` in the codebase. I'm sure it's used by some of our dependencies (e.g. Ray) but, well, they can pull them in if needed transitively.

`awscli` is needed by some scripts in `experiments/*.sh` but it seems harmless to make this optional -- we can always add a check to the scripts to give the user a friendly error message with installation instructions.

**Comment by shwang** [comment]
I think we used `cloudpickle` for an annoying pickle job in the past. If it's no longer in the codebase that should be safe to remove.

`awscli` is only used by download.sh IIRC.
