### ISSUE TITLE
Fixing compatability with call to torch.distributions.Bernoulli() for pytorch 1.9.0

### ISSUE THREAD

**Issue by mbeliaev1** [HumanCompatibleAI/imitation#318]
Thank you for your work on this library! 

I have run into an issue trying to implement AIRL for my own custom environment, but I believe the solution is quite simple.  It is most likely that this issue is due to me using a newer version of pytorch (1.9.0 to be exact), and hence this may not be something of importance to you. Either way, I found the fix to be quite intuitive and thought I would share just in case you or anyone else finds this useful:
 
In **line 135** of **imitation/src/imitation/rewards/common.py**:

`label_dist = th.distributions.Bernoulli(disc_logits_gen_is_high)`
should be changed to 
`label_dist = th.distributions.Bernoulli(logits=disc_logits_gen_is_high)`

Basically, pytorch automatically assumes that disc_logits_gen_is_high is a probability distribution, hence the error. 

The entire error message without this change is:
```python
ValueError                                Traceback (most recent call last)
<ipython-input-7-1a31953e8f5e> in <module>
     12     gen_algo=policy,
     13 )
---> 14 airl_trainer.train(total_timesteps=2048)

~/anaconda3/envs/my_env/lib/python3.9/site-packages/imitation/algorithms/adversarial.py in train(self, total_timesteps, callback)
    307             self.train_gen(self.gen_batch_size)
    308             for _ in range(self.n_disc_updates_per_round):
--> 309                 self.train_disc()
    310             if callback:
    311                 callback(r)

~/anaconda3/envs/my_env/lib/python3.9/site-packages/imitation/algorithms/adversarial.py in train_disc(self, expert_samples, gen_samples)
    233             # compute/write stats and TensorBoard data
    234             with th.no_grad():
--> 235                 train_stats = rew_common.compute_train_stats(
    236                     disc_logits, batch["labels_gen_is_one"], loss
    237                 )

~/anaconda3/envs/my_env/lib/python3.9/site-packages/imitation/rewards/common.py in compute_train_stats(disc_logits_gen_is_high, labels_gen_is_one, disc_loss)
    133         generated_acc = _n_pred_gen / float(_n_gen_or_1)
    134 
--> 135         label_dist = th.distributions.Bernoulli(disc_logits_gen_is_high)
    136         entropy = th.mean(label_dist.entropy())
    137 

~/anaconda3/envs/my_env/lib/python3.9/site-packages/torch/distributions/bernoulli.py in __init__(self, probs, logits, validate_args)
     46         else:
     47             batch_shape = self._param.size()
---> 48         super(Bernoulli, self).__init__(batch_shape, validate_args=validate_args)
     49 
     50     def expand(self, batch_shape, _instance=None):

~/anaconda3/envs/my_env/lib/python3.9/site-packages/torch/distributions/distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     51                     continue  # skip checking lazily-constructed args
     52                 if not constraint.check(getattr(self, param)).all():
---> 53                     raise ValueError("The parameter {} has invalid values".format(param))
     54         super(Distribution, self).__init__()
     55 

ValueError: The parameter probs has invalid values
```

**Comment by AdamGleave** [comment]
Thanks for the detailed bug report. I agree this change seems needed for recent versions of PyTorch. Can you open a PR for this change?

**Comment by mbeliaev1** [comment]
Sure thing! I will create the PR on Monday.

**Comment by mbeliaev1** [comment]
It seems like PR #273 has fixed this issue. Not sure why I was getting an older version installed with pip. No need to make a new PR as the current main branch already has this fix implemented.

**Comment by DavidChiumera-404** [comment]
Was this ever resolved? I am having the same issue with my own custom env. @AdamGleave

**Comment by AdamGleave** [comment]
@DavidChiumera-404 are you seeing this issue on `master`? We still need to make a new PyPi release, but I'm planning on waiting until all the major ongoing changes we're making are finished first.
