### ISSUE TITLE
[Bug] wrong input size for MLP in BasicRewardNet for MultiDiscrete action space

### ISSUE THREAD

**Issue by Abermal** [HumanCompatibleAI/imitation#369]
### 🐛 Bug

`imitation.rewards.reward_nets.BasicRewardNet` calculates wrong input size

In order to calculate `combined_size` (input size) a `stable_baselines3.common.preprocessing.get_flattened_obs_dim` is used.
However it behaves incorrectly and for a `MultiDiscrete([3 3])` action space returns `6`, instead of `2`.

Which leads to:
```bash
...\imitation\src\imitation\rewards\reward_nets.py in forward(self, state, action, next_state, done)
    310         inputs_concat = th.cat(inputs, dim=1)
    311 
--> 312         outputs = self.mlp(inputs_concat)
    313         assert outputs.shape == state.shape[:1]
...
   1845     if has_torch_function_variadic(input, weight):
   1846         return handle_torch_function(linear, (input, weight), input, weight, bias=bias)
-> 1847     return torch._C._nn.linear(input, weight, bias)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x50 and 54x32)
```
Note: the observation dim is `48` and the resulting concatenated dim should be equal to `48 + 2 = 50`

I've created an [issue](https://github.com/DLR-RM/stable-baselines3/issues/609) at stable-baselines3 describing this problem, but I think it can be fixed locally by using the `get_obs_shape` instead.

I can provide an example if needed.
Once again, thank you for your work.

**Comment by Abermal** [comment]
Current workaround
```python
from imitation.rewards import reward_nets

reward_net = reward_nets.BasicShapedRewardNet(
    observation_space=venv.observation_space,
    action_space=venv.action_space, 
    use_action=False
)

airl_logger = logger.configure(tempdir_path / "AIRL/")
airl_trainer = airl.AIRL(
    venv=venv,
    demonstrations=transitions,
    demo_batch_size=batch_size,
    gen_algo=sb3.PPO("MlpPolicy", venv, verbose=1, n_steps=1024),
    reward_net=reward_net,
    allow_variable_horizon=True,
    custom_logger=airl_logger,

)
```

**Comment by AdamGleave** [comment]
Closing as do not have information needed to replicate this.

**Comment by Juphex** [comment]
Is there also a workaround for BC?
