### ISSUE TITLE
Not support Dict space observation

### ISSUE THREAD

**Issue by Leong1230** [HumanCompatibleAI/imitation#372]
Hi!
It seems that classes in 'imitation/data/types.py' like Transitions and Trajectory don't support spaces.Dict observation. In my case, the obs contain data in different dimensions from different sensors. How can I work with such an expert dataset with this repo? Could you please offer some examples?
Thank you!

**Comment by AdamGleave** [comment]
You're right this is a limitation. We'd like to add support for `Dict` spaces, but note this will require changes to the algorithms as well as the data structures. PRs are welcome on this.

The easiest workaround is to make an environment wrapper to flatten the dict observations into a single NumPy array.

**Comment by Leong1230** [comment]
Thank you for your prompt reply! Looking forward to the update!

**Comment by akmandor** [comment]
Is there any update on Dict space support?

**Comment by AdamGleave** [comment]
We still do not currently support `Dict` spaces. PRs are welcome on this. As I mentioned flattening dict observations is usually a viable workaround.

**Comment by malwaru** [comment]
> By flattening dict observations, do you mean concatenating them? My env produces the following observations {x: [Nx1], adj: [Mx1], mask: [Px1]} Should this be converted into [N+M+Px1]?
> 
> Thanks

Did this work for you . Flattening it like this ?
