### ISSUE TITLE
Question about GAIL for classic control

### ISSUE THREAD

**Issue by ebuehrle** [HumanCompatibleAI/imitation#380]
What kinds of average rewards would be expected for GAIL on Pendulum-v0, seals/CartPole-v0 or seals/MountainCar-v0 (or MountainCarContinuous-v0)? Also, are there recommended hyperparameters for GAIL on Pendulum-v1?

**Comment by AdamGleave** [comment]
Sorry for the slow response here.

We're planning on doing comprehensive benchmarking soon, releasing results + hyperparams and accompanying paper.

In the meantime here's a table of results from an internal test run:
![image](https://user-images.githubusercontent.com/1547683/150065521-5bb9a845-fbc1-4f60-aeb3-e63dd1bd1cc1.png)

I'd expect similar hyperparams to work between `Pendulum-v1` and `Pendulum-v0`; I don't think we've tested `Pendulum-v1` specifically.

**Comment by gunnxx** [comment]
Hi @AdamGleave , any follow up on this? I am curious about the expert data efficiency claim in GAIL.
