### ISSUE TITLE
Fix mce_irl.ipynb notebook + add tests

### ISSUE THREAD

**Issue by prasuchit** [HumanCompatibleAI/imitation#381]
Hi,

I've installed the library successfully and the basic commands in the readme work perfectly fine. My plan is to build my own custom MDP envs to use with AIRL. However, since my MDP is a discrete space one, I wanted to first test out the Cliffworld example given under imitation/envs/examples/model_envs.py. I'm trying to use the mce_irl.ipynb in experiments folder. However, it still imports tabular_irl.py and even if I rename the import, it uses the LinearRewardModel from the removed file.

Kindly help.

**Comment by prasuchit** [comment]
@AdamGleave @shwang please provide help on how to run your example scripts. Some of them complain about missing pkl files while others import and use missing modules. 

I would like to build my own MDP and test using your library, but first I need to understand how your package works. I would be adding multi-agent envs and solvers to this and will raise a PR in the future. Kindly help me get started. Thanks.

**Comment by AdamGleave** [comment]
Thanks for raising the issue, looks like we broke `mce_irl.ipynb` in a recent refactor and didn't catch it as it's not part of the unit tests. Unfortunately I likely won't have time to get around to fixing this until the new year. But you can see some examples of working code using MCE IRL in https://github.com/HumanCompatibleAI/imitation/blob/master/tests/algorithms/test_mce_irl.py The key change (apart from renaming the import, as you suggested) will be to switch out LinearRewardModel for `reward_nets.BasicRewardNet` with `hid_sizes=[]` (an MLP with no hidden units is linear), ala https://github.com/HumanCompatibleAI/imitation/blob/master/tests/algorithms/test_mce_irl.py#L327

Hope this helps.

**Comment by AdamGleave** [comment]
Hoping to get to this soon. Main things we should do:
  - [ ] Fix mce_irl.ipynb based on new MCE IRL API.
  - [ ] Move from `experiments/` to `examples/` -- it's not an experiment for anything, it's just an example use case.
  - [ ] Add it to automated test suite via `tests/test_examples.py` so we won't break it again.

**Comment by AdamGleave** [comment]
Update on this: we now have a [notebook](https://github.com/HumanCompatibleAI/imitation/blob/master/examples/6_train_mce.ipynb) in examples that does work. It's still missing a few interesting parts from `experiments/mce_irl.ipynb`, though. So I think we should port those over, and then delete `mce_irl.ipynb`.
