### ISSUE TITLE
Expand quickstart tutorials

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#383]
We currently have a brief (<70 LOC) [quickstart](https://github.com/HumanCompatibleAI/imitation/blob/master/examples/quickstart.py) Python file, illustrating some simple uses of the API. This is helpful, but it (a) doesn't walk the user through very much; (b) misses a lot of important features of the API, e.g. serializing and deserializing reward models and policies.

It would be nice to have more examples in the docs for common use cases, and a series of Jupyter notebook tutorials similar to the [SB3 RL tutorial](https://github.com/araffin/rl-tutorial-jnrr19/tree/sb3). Although as an initial step, I think it's best to err on the side of a fairly small tutorial, and we can then expand as we get feedback from users on what's confusing.

**Comment by ernestum** [comment]
- quickstart.py should be actually quick. Therefore a simple< 20 loc example to demonstrate that imitation works in the most basic setting. Render a trajectory before training and one after to show that it actually works. This is a very light example with big "entertainment factor".
- train_using_{algo}.py for algo in [BC, DAgger, density, MCE, AIRL, GAIL, preferences]. To introduce all the algorithms with their individual quirks. Can be longer and with more explanations.
- warm_start.py Examples showing training an algorithm warm-started from a previously trained reward model and/or policy using AIRL.
- pause_and_resume.py demonstrating serialization of reward models and policies.
- data_analysis.py demonstrating how to visualize data e.g. rollout.rollout_stats.
