### ISSUE TITLE
API reference for all algorithms

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#384]
In `docs/algorithms`, we need to add entries for:

  - [x] MCE IRL
  - [x] Preference Comparison
  - [x] Density Baseline

We should also add an introduction/basic guidance to the existing algorithms that are (somewhat) documented:

  - [ ] Behavioral Cloning
  - [ ] GAIL
  - [ ] AIRL
  - [ ] DAgger

Additionally, we should add to the docs and `README.md` a:

  - [x] Table summarizing all algorithms similar to in the [SB3 docs](https://stable-baselines3.readthedocs.io/en/master/guide/algos.html). Should include citations to the original papers; any restrictions on supported observation/action space; whether it returns a reward or just a policy; possibly other columns?

**Comment by Rocamonde** [comment]
First and last parts fixed by #484. Maybe we can spin off the rest (i.e. adding actual text to the algos apart from just an entry in the docs) to a separate issue.

**Comment by Rocamonde** [comment]
@AdamGleave  is "Deep reinforcement learning from human preferences" the algo "preference comparison"? Cannot find a clear connection between both or between any other paper/algo.

**Comment by AdamGleave** [comment]
> @AdamGleave is "Deep reinforcement learning from human preferences" the algo "preference comparison"? Cannot find a clear connection between both or between any other paper/algo. Also, do we have a paper link to 'density-based reward modeling' and to behavioral cloning?

Yes, they're the same algorithm, modulo a few minor implementation differences.
