### ISSUE TITLE
Write developer guide

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#385]
Add a guide e.g. `docs/guide/developer.rst` summarizing the internals of `imitation` and guidelines for new developers building off [CONTRIBUTING.md](https://github.com/HumanCompatibleAI/imitation/blob/master/CONTRIBUTING.md).

Examples of developer guides: [SB3](https://stable-baselines3.readthedocs.io/en/master/guide/developer.html), [NumPy](https://numpy.org/doc/stable/dev/) and [pandas](https://pandas.pydata.org/docs/development/index.html) (last two are more elaborate than we need)

**Comment by Rocamonde** [comment]
Related: #484 (#483). Would be a nice next step after 484 gets merged. There are a few things to polish in the contributors guidelines, especially when it comes to development guidelines and integrating it with the developer installation/setup process.

**Comment by AdamGleave** [comment]
Completed now.
