### ISSUE TITLE
Official support for Windows & Mac

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#386]
Given a lot of people use Windows or Mac for development, it'd be nice if `imitation` could reliably support this. We don't use any Linux/BSD-specific features. Moreover, PyTorch and even MuJoCo support Windows and Mac, so this should require minimal (if any) porting.

To make sure we don't break it in the future, it'd be good to add continuous integration testing for these platforms. CircleCI supports [Mac and Windows executors](https://circleci.com/docs/2.0/executor-intro/), so I think it's just a matter of adding versions of the current [`unit-test` job](https://github.com/HumanCompatibleAI/imitation/blob/dbd26c889c36d70bf0eef42dd44f050a7d328541/.circleci/config.yml#L127) for these platforms. The complicating factor will be that we'll need to setup the binary environment to support what we need -- probably we just want to skip MuJoCo and all the nasty graphics dependency it pulls in? Might want to run an abbreviated version of the test suite on these anyway, both because CircvleCI [pricing](https://circleci.com/product/features/resource-classes/) is a lot higher for Windows/Mac and to not slow down the CI test too much.

**Comment by Rocamonde** [comment]
Related: #477 and #476.

**Comment by AdamGleave** [comment]
We now have CI on Windows, everything is working apart from some bash scripts (that are not a core part of the library) and the need to enable developer mode to get symlinks to work (needed by some of our scripts).

Only thing remaining is to add Mac CI (which I expect should be easier as POSIX compliant), and document Windows/Mac installation.
