### ISSUE TITLE
[Question] Can I save the BC model at different times during training?

### ISSUE THREAD

**Issue by cristinagatt** [HumanCompatibleAI/imitation#416]
Apologies for asking such a question but is it possible that I save the Behavioral Cloning model at different times during training? For example: Can I save the model after 1000 epochs of training and then save it again after 2000 epochs in the same training session?

**Comment by AdamGleave** [comment]
Yes, `save_policy` can be called at any point during training. You can either use the `on_epoch_end` callable or just call `train` for 1000 epochs, save, and then call it again for another 1000 epochs (in your example).

**Comment by cristinagatt** [comment]
Thank you! That worked perfectly. If I may ask another question... Is it possible to integrate Tensorboard while training BC? I saw that there is a parameter that mentions tensorboard but I did not manage to make it work for me as tensorboard still shows nothing when called. 

Thank you.
