### ISSUE TITLE
I want to use my own expert trajectories

### ISSUE THREAD

**Issue by strangeppeo** [HumanCompatibleAI/imitation#432]
Hi! These trajectories are not generated by gym.These trajectories are divided into strips, which are known state-action pairs, stored as numpy arrays. I didn't find a way to convert them to types.TrajectoryWithRew. I beg you to help me with this.

Do I need to convert it to the form of rollout.rollout？If i need, how can i do this operation .Thank you .

**Comment by strangeppeo** [comment]
There are a few more details, I'm new to AIRL, these trajectories are from a set of robot trajectories optimized mathematically, and I want to see if I can use this method to improve the central controller on the robot with AIRL. In addition, I saw a question on February 14th in the closed question. I think the control amount output by AIRL can be compared with the control amount of the expert trajectory provided, and the terminal situation should be added to the judgment. It can be evaluated AIRL's ability to solve practical problems.

**Comment by AdamGleave** [comment]
You'll need to perform the conversion to `types.Trajectory` (or `types.Transition` also works for some algorithms). There are lots of ways to represent trajectories, so we naturally cannot provide conversions from arbitrary types. If there's a specific area where the type signature of our data classes is unclear let us know, happy to consider revising the documentation.

**Comment by strangeppeo** [comment]
thank you very much. To be more detailed, what are the conversion tools that can complete the above conversion you mentioned?

**Comment by ejnnr** [comment]
> what are the conversion tools that can complete the above conversion you mentioned?

Not sure if this is what you're asking, but you can create a trajectory simply by
```python
traj = Trajectory(observations, actions, infos=None, terminal=True)
```
(assuming it's one or more complete episodes). `observations` and `actions` are simply numpy arrays, see https://github.com/HumanCompatibleAI/imitation/blob/48de6c4dc933b4af75ed259119cfb36fcdb6bdcb/src/imitation/data/types.py#L45 for details. How to get these numpy arrays for observations and actions of course depends on the format your trajectories are in, as Adam said `imitation` doesn't have functions for that.

**Comment by strangeppeo** [comment]
My problem has been completely solved by AdamGleave and ejnnr's answers. Thanks again for your contributions to this code!
