### ISSUE TITLE
[Question]Talk About Rewards

### ISSUE THREAD

**Issue by strangeppeo** [HumanCompatibleAI/imitation#435]
In [imitation](https://github.com/HumanCompatibleAI/imitation)/[examples](https://github.com/HumanCompatibleAI/imitation/tree/master/examples)/4_train_airl.ipynb ,finally we use "from stable_baselines3.common.evaluation import evaluate_policy" to test the agent .However, as i know, many times(unlike original environment), we can't get a explicit expression about rewards, so write own gym environment doesn't have the rewards.(In order to conform to the gym code format, I set this reward as a constant 0.5).
So if i want to test the agent, i must need to use reward from Discriminator's reward network. In running code ,how can i do this.

**Comment by AdamGleave** [comment]
You can use the [RewardVecEnvWrapper](https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/rewards/reward_wrapper.py#L36)

But I'm not sure evaluating the agent by looking at discriminator output will tell you what you want. For one, at convergence of GAIL, the discriminator output will itself be constant. AIRL is better behaved here, but you'll just be testing if the policy does what the learned reward thinks is good, which may not correspond to what's actually good -- so it's not an independent source of evidence. Your best option may be to manually inspect the rollouts (e.g. by making a video render of it) and have human evaluation.

**Comment by reneelin1712** [comment]
> You can use the [RewardVecEnvWrapper](https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/rewards/reward_wrapper.py#L36)
> 
> But I'm not sure evaluating the agent by looking at discriminator output will tell you what you want. For one, at convergence of GAIL, the discriminator output will itself be constant. AIRL is better behaved here, but you'll just be testing if the policy does what the learned reward thinks is good, which may not correspond to what's actually good -- so it's not an independent source of evidence. Your best option may be to manually inspect the rollouts (e.g. by making a video render of it) and have human evaluation.

In RewardVecEnvWrapper, is the reward_fn I need to provide?

But according to the paper, the reward_net/discriminator consist of two networks, one is reward network, the other is value network. After the reward_net is obtained, how can I get this reward network that only takes in states and output a reward/score? Based on this obtained reward network I could train the agent without any provided reward_fn I created.

**Comment by AdamGleave** [comment]
The `reward_test` attribute of `AIRL` gives the one that is unshaped, [here](https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/algorithms/adversarial/airl.py#L94), while the `reward_train` gives the shaped version. It is not state-only by default (note although the AIRL paper talks about state-only extensively, many of the experiments in that paper used state-action rewards), but you can configure it to be so using the keyword arguments to `build_mlp`.

In practice I find training with `reward_test` often doesn't produce a good policy, though works OK in some environments. As far as we can tell that's an issue with the algorithm itself, not this implementation.
