### ISSUE TITLE
How can I resolve " AttributeError: module 'imitation.data.rollout' has no attribute 'rollout' " ? 

### ISSUE THREAD

**Issue by reneelin1712** [HumanCompatibleAI/imitation#436]
I installed the imitation package and try the notebook under the examples folder, 1_train_bc.ipynb, but I came across this error, what can I do? Thanks in advance.

**Comment by AdamGleave** [comment]
Can you provide some details of your installation environment, and the full stack trace? The notebooks are covered by unit tests so this should not happen. Is it possible you installed a different version of `imitation` to the notebook you are running?

**Comment by reneelin1712** [comment]
> Can you provide some details of your installation environment, and the full stack trace? The notebooks are covered by unit tests so this should not happen. Is it possible you installed a different version of `imitation` to the notebook you are running?

Hi, I tried both Google Colab and my local environment. I just opened the Jupyter Notebook and install imiation.
Colab:
Python Version- 3.7.13
imitation   0.2.0
gym 0.17.3
stable-baselines3    0.8.0

local Jupyter Notebook using Anaconda:
Python Version- 3.9.7
imitation             0.2.0
gym                    0.21.0
stable-baselines3    0.8.0

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-bc2f028909eb>](https://localhost:8080/#) in <module>()
      3 from stable_baselines3.common.vec_env import DummyVecEnv
      4 
----> 5 rollouts = rollout.rollout(
      6     expert,
      7     DummyVecEnv([lambda: RolloutInfoWrapper(env)]),

AttributeError: module 'imitation.data.rollout' has no attribute 'rollout'

**Comment by AdamGleave** [comment]
You will need to install `imitation` from the GitHub master branch, you can follow the instructions in the [README](https://github.com/HumanCompatibleAI/imitation#install-latest-commit). The latest version on PyPi is not compatible with these notebooks. We do intend to make a new release soon :)
