### ISSUE TITLE
`train_rl.py` depending on `rewards.serialize` still uses unnormalized reward

### ISSUE THREAD

**Issue by yawen-d** [HumanCompatibleAI/imitation#437]
## Background

#425 applied changes to save a `NormalizedRewardNet` containing an additional normalized layer and its norm statistics. The current state of `imitation.rewards.reward_nets` is as follows:

- `RewardNet` ABC, with `predict_processed` concrete implementation that just calls `predict`.
    - `BasicRewardNet` concrete implementation.
- `RewardNetWrapper` is ABC underneath `RewardNet`, taking `base`: `RewardNet` constructor argument and exposing base attribute.
    - `ShapedRewardNet` is ABC, for adding shaping in general.
        - `BasicShapedRewardNet` concrete implementation using MLP for potential shaping.
- `NormalizedRewardNet` is a concrete implementation, to implement `forward` as well as `predict_processed` that uses normalization layer given by normalize_class, like `NormalizeFeaturesExtractor`.

In `NormalizedRewardNet`, there are three methods that can output reward.
1. [`forward()`](https://github.com/HumanCompatibleAI/imitation/blob/f332680115380ce654cfd061fbaaa7bc47918d2c/src/imitation/rewards/reward_nets.py#L378) returns unnormalized reward (torch.Tensor) with gradient.
2. [`predict()`](https://github.com/HumanCompatibleAI/imitation/blob/f332680115380ce654cfd061fbaaa7bc47918d2c/src/imitation/rewards/reward_nets.py#L143) returns unnormalized reward (numpy.array) without gradient.
3. [`predict_processed()`](https://github.com/HumanCompatibleAI/imitation/blob/f332680115380ce654cfd061fbaaa7bc47918d2c/src/imitation/rewards/reward_nets.py#L347) returns normalized reward (numpy.array). Note that `predict_processed()` contains a `update_stats` (default to be `True`) argument to determine whether to update the norm stat or not.

Notably, `NormalizedRewardNet` is only used in `preference_comparisons`. The reason why we have this implementation is that we would like to return normalized reward and update norm stats during [RL training](https://github.com/HumanCompatibleAI/imitation/blob/f332680115380ce654cfd061fbaaa7bc47918d2c/src/imitation/algorithms/preference_comparisons.py#L145). During [reward model training](https://github.com/HumanCompatibleAI/imitation/blob/f332680115380ce654cfd061fbaaa7bc47918d2c/src/imitation/algorithms/preference_comparisons.py#L763), the model returns unnormalized reward with gradient from `forward()`.

## Implications
Now we can save a `NormalizedRewardNet` with the normalization layer within a single file. The next step would be to update the `_load_reward_net_as_fn()` that loads a RewardNet as a function. Ideally, we should achieve the following goal:
In `train_rl.py`, we could load a `NormalizedRewardNet`, reset it's norm stat instead of [wrapping the `venv` with a `VecNormalize`](https://github.com/HumanCompatibleAI/imitation/blob/f332680115380ce654cfd061fbaaa7bc47918d2c/src/imitation/scripts/train_rl.py#L104).

@AdamGleave @levmckinney Welcome more thoughts on this.

**Comment by AdamGleave** [comment]
- No need to be able to reset running average.
  - Should be able to handle the case where something is both shaped and normalized, and be able to get the shaped + normalized, shaped + unnormalized version or unshaped + unnormalized version.
  - The unshaped + normalized version is tricky. The normalization statistics are simply not meant for that. Least-bad option is probably to just copy over the normalization statistics, but I'd also be fine with just not supporting it, and that might be better if the implementation ends up looking complex.

**Comment by yawen-d** [comment]
Thank you both for working on the issue! @levmckinney @AdamGleave
