### ISSUE TITLE
EMA Reward Normalization

### ISSUE THREAD

**Issue by levmckinney** [HumanCompatibleAI/imitation#441]
# Feature Request
An exponential moving average normalization layer. 
### Current Behavior
The current behavior of the running normalization layer `RunningNorm` is to compute a running sample mean and variance.
### Expected Behavior
There should be an exponential moving average Normalization layer that computes the mean and variance of the features based on an exponentially waited sample mean and variance.

### Motivation

Throughout the process learning a reward function and policy the reward distribution will change due to changes in the reward network and the policy. Thus, the samples output by the reward network are not actually i.i.d over the course of training.  Therefor, when using  a running mean and variance to normalize rewards the algorithm puts too much weight on samples from early in reward function learning when the distribution of rewards was very different. Using an exponentially weighted moving average to compute the normalization statistics could fix this problem by putting more weight on recent samples.

**Comment by AdamGleave** [comment]
Fixed in #443
