### ISSUE TITLE
Preference Comparisons Improvement

### ISSUE THREAD

**Issue by SugarmanZhu** [HumanCompatibleAI/imitation#450]
For the [preference comparisons notebook example](https://github.com/HumanCompatibleAI/imitation/blob/59d474988c744c27fe4b5e6494170eeba14207eb/examples/5_train_preference_comparisons.ipynb)
In the last cell, the agent's policy is used to evaluate but it should be using learner's policy instead.

I suggest changing
`reward, _ = evaluate_policy(agent.policy, venv, 10)` 
to
`reward, _ = evaluate_policy(learner.policy, venv, 10)`

**Comment by AdamGleave** [comment]
Good catch, can you open a PR for this?
