### ISSUE TITLE
`test_mce_irl_reasonable_mdp` is not consistently passing

### ISSUE THREAD

**Issue by levmckinney** [HumanCompatibleAI/imitation#463]
`test_mce_irl_reasonable_mdp` is randomly failing about 27% of the time on master. I don't know when this was introduced due to its random nature. It should be fixed asap since it is causing unrelated pull request's CI jobs to fail.

## To replicate
```bash
git checkout master # at 0381232b1b90c28d1dd581857659d2649a5dbb9c when writing this issue.
```
Run the following script.
```bash
#!/bin/bash
N=100
for i in $(seq 1 $N); do
    if ! pytest tests/algorithms/test_mce_irl.py -k test_mce_irl_reasonable_mdp; then failed=$(expr $failed + 1); fi
done
echo $failed / $N
```
Note this will take a little while.
## Expected behavior
This test should pass or fail 100% of the time.

**Comment by AdamGleave** [comment]
Thanks for flagging this, agreed we should fix it asap.

As an aside, I like [pytest-flakefinder](https://pypi.org/project/pytest-flakefinder/) for catching things like this.
