### ISSUE TITLE
DiscrimNet nomenclature referring to AdversarialTrainer class

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#468]
In the following docstring:

https://github.com/HumanCompatibleAI/imitation/blob/2a383ebfeef1753a9538435cb35e7b1f7f0ddb80/src/imitation/algorithms/adversarial/common.py#L23-L35

Should line 32 not refer to the class `AdversarialTrainer` instead of `DiscrimNet`, which in my understanding is not to be found anywhere in the repo? (apart from line 79 in a docstring within `scripts/train_adversarial.py` file). That is where the `logits_gen_is_high` function is found. 

I am asking because the AdversarialTrainer class is not a torch module, which is what the `<>Net` notation suggests based on other classes.

Happy to change this myself if this was just an errata.

**Comment by Rocamonde** [comment]
On a second quick look, it seems that this naming convention was present in past commits when such a class did exist? So should be a question of updating any remnant references to it adequately. 

In the future, when deleting a symbol, IMHO it might be worth doing a global search to make sure that no references to the symbol on docstrings are left. (There are extensions that do this, but this is more workflow-dependent).

**Comment by AdamGleave** [comment]
Well spotted. Yes `DiscrimNet` is a class that used to exist that we removed, that was a hybrid of current `RewardNet` and `AdversarialTrainer` functionality.

Updating this to point to `AdversarialTrainer` seems like the right solution.

I already use a PyCharm workflow that should flag things like this as errors under "safe delete". If there's an easy way to add a check like this to CI then I'd be happy to see that. We could perhaps also go the route of having more exhaustive docstring linting to catch references to undefined symbols.
