### ISSUE TITLE
Wrong type passed into _torchify_array on adversarial/common.py

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#469]
In the snippet below:
https://github.com/HumanCompatibleAI/imitation/blob/2a383ebfeef1753a9538435cb35e7b1f7f0ddb80/src/imitation/algorithms/adversarial/common.py#L563-L566
the variable `labels_expert_is_one` is indeed an NDArray; however, `log_policy_act_prob` is already (afaik) a torch tensor. There is no need to torchify it, and it gives a type error since `_torchify_array` only takes in np.ndarray objects (or None).

I see two courses of action:
1. Remove the torchify call after making sure that log_policy_act_prob is indeed always a tensor (seems the most logical thing to do IMO)
2. Only overload the type of _torchify_array (I think torch.as_tensor is idempotent) / change function body + signature to do nothing if the input is already a tensor, and call the function anyways there and potentially in other places (seems "safer" but overly cautious and unclean).

Happy to provide a fix for this whatever way is preferred by others.

**Comment by AdamGleave** [comment]
Thanks for catching this. Option 1 seems the right call to me. I don't even feel the need to do a runtime check here per se; `_get_log_policy_act_prob` would have to violate its contract to return something that's not a Tensor, and since it's part of our class I'm OK depending on it, though I don't object to adding an assertion.

Did you spot this manually, or do you have some static analysis tool that caught it? `pytype` clearly didn't spot this given CI passes.

**Comment by Rocamonde** [comment]
Hi, thanks. I spotted this with Visual Studio Code's Pylance language server. I actually see x10 times as many type errors as I have bothered to fix, some of which are due to Pylance trying to be too smart. To be honest, I'm not a big fan of `pytype`, only used it once or twice and have found other type checkers to be better. I guess that's a discussion for another time, but it might be worth going over what linters and type checkers we have in the pipeline. 

There's a lot of red in my editor of using Tensor and np.ndarray types interchangeably and that can cause inefficiencies in having to move data from the CPU to the GPU and back, and converting the types. (based on my first impression most are actually that the method that gets called is too restrictive in the type and requires ndarray or vice versa when the duck-type operations would work on both just fine, but it's worth making sure).

**Comment by AdamGleave** [comment]
I tried Pylance a couple of years back and got annoyed by the false positives, but perhaps it's improved. Happy to try out new things in the CI pipeline, and there's no reason we can't use multiple type checkers, they all have their strengths and weaknesses.
