### ISSUE TITLE
Inconsistent callback timesteps between different RL algorithms in `scripts/data_collect.py`

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#47]
Adam:
Since `step` is the number of times `callback` has been invoked, `rollout_save_interval` is going to have radically different meanings between RL algorithms and depending on hyperparameters. Some RL algorithms, e.g. `DQN`, call `callback` after each timestep! Others, e.g. `PPO2`, only invoke `callback` after each batch.

I solved this in https://github.com/HumanCompatibleAI/adversarial-policies/blob/master/src/modelfree/train.py by specifying a variable name and multiplier for each RL algorithm, such that the variable value in `locals_` times the multiplier equals the number of elapsed training steps. Plausibly we should patch Stable Baselines so that it always calls `callback` with some `steps_elapsed` parameter?

_Originally posted by @AdamGleave in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjYxNTc0OTQ3/pull_request_reviews/more_threads_

**Comment by AdamGleave** [comment]
Stable Baselines 2.10 adds a new callback interface to solve exactly this kind of issue.

**Comment by AdamGleave** [comment]
Closing as `scripts/data_collect.py` doesn't even exist any longer...
