### ISSUE TITLE
Improve README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#483]
Currently, the entry point for new users to learn, explore and contribute to imitation are the README.md and CONTRIBUTING.md files. I think these can be improved in several ways, which I am happy to contribute to. See below for some suggestions:

1. The README.md file should be a summary of relevant links within the project. I personally dislike very long README.md repo files that include unnecessary detail, as I think it can be confusing for users who are not already familiar with the project. 
     - [x] Add a table of algorithms implemented, with a link to the paper, the API docs (and ideally a tutorial on how to use it). Below this table we can have a link to add algorithm requests.
     - [x] Add a link to the release notes. 
     - [x] Add release notes to the docs.
2. The CONTRIBUTING.md file should be more welcoming to new-comers, and cover a range of cases.
     - [x] Provide guidance on submitting bug repots, feature requests, documentation and code PRs
     - [x] Add a FAQ page so that users can add PRs to things they've struggled with
     - [ ] Add a few FAQs ourselves. 
     - [x] We would need a minimal code of conduct and a notice disclosing the IP / licensing issues when users' contributions are merged into the codebase.
     - [ ] Add issue templates (tried to do this but only repo admins can, as it's under settings) so that users have a ready-to-use structure with reminders on things to include.

Keen to hear what others think about the above!

**Comment by AdamGleave** [comment]
Thanks Juan, I largely agree with this. I will say that the current README doesn't feel overly long to me, so I'm not in a mood to cut things right now, but I do generally agree with the vision of having the README be short and to the point and deferring more lengthy discussion to docs.

> We should add issue templates (tried to do this but only repo admins can, as it's under settings) so that users have a ready-to-use structure with reminders on things to include.

Although this is how the GitHub web UI works, I think under the hood it just makes a `.github/ISSUE_TEMPLATE` directory, and you can make a PR for those without admin permissions. You could use something like https://github.com/DLR-RM/stable-baselines3/tree/master/.github/ISSUE_TEMPLATE as an example

**Comment by Rocamonde** [comment]
Sounds good, updated the checklist with your feedback. re: the issue templates, I think you're right that you can simply commit them to `.github/ISSUE_TEMPLATE`, but it seems like it's easier to create/manage from the settings. I'll take another look later
