### ISSUE TITLE
 Logits sign convention miscellaneous fixes

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#496]
This issue brings up some fixes suggested by Adam that were left out of #472.

 - [x] ensure that math renders correctly in the docs for GAIL/AIRL docs
 - [x] [src/imitation/algorithms/adversarial/airl.py](https://github.com/HumanCompatibleAI/imitation/pull/472/files/f09bd9d33bc108ea06b077885d502bfcf5143022#diff-96a2e99f7d151f9a320991330c80e7d748659c89facfc57f7f5f2ba6f6cbbece) "by the generator, \log { \pi(a|s) }."
 - [x] [src/imitation/algorithms/adversarial/airl.py](https://github.com/HumanCompatibleAI/imitation/pull/472/files/f09bd9d33bc108ea06b077885d502bfcf5143022#diff-96a2e99f7d151f9a320991330c80e7d748659c89facfc57f7f5f2ba6f6cbbece) "You don't check it's a tensor, just that it's not none."
 - [x] [src/imitation/algorithms/adversarial/gail.py](https://github.com/HumanCompatibleAI/imitation/pull/472/files/f09bd9d33bc108ea06b077885d502bfcf5143022#diff-2853b8a6227ff6268d154f6eccb3ab6d79bf7e48852535c8304be19308f236be) Violates style guide
 - [x] [src/imitation/algorithms/adversarial/gail.py](https://github.com/HumanCompatibleAI/imitation/pull/472/files/f09bd9d33bc108ea06b077885d502bfcf5143022#diff-2853b8a6227ff6268d154f6eccb3ab6d79bf7e48852535c8304be19308f236be) "... to use the opposite convention that ..."

**Comment by Rocamonde** [comment]
@AdamGleave why are we accepting the parameter `log_probability_act_prob` in this class 
https://github.com/HumanCompatibleAI/imitation/blob/242b15bd70a9278e4477b4197ffd9ee50fcda5b9/src/imitation/algorithms/adversarial/gail.py#L142
if we then go and directly delete it in the first line of code within the method scope? 
https://github.com/HumanCompatibleAI/imitation/blob/242b15bd70a9278e4477b4197ffd9ee50fcda5b9/src/imitation/algorithms/adversarial/gail.py#L158
If this is because the class must conform to a certain protocol, maybe we want to define the protocol for clarity? It feels quite silly otherwise.

**Comment by Rocamonde** [comment]
Another note. You mentioned:

> You don't check it's a tensor, just that it's not none.

regarding 

https://github.com/HumanCompatibleAI/imitation/blob/242b15bd70a9278e4477b4197ffd9ee50fcda5b9/src/imitation/algorithms/adversarial/airl.py#L107

(on https://github.com/HumanCompatibleAI/imitation/pull/472#discussion_r927051214_). Why is it particularly useful to check that this argument, which is typed as a tensor, is indeed a tensor? Does not seem consistent to randomly check the type of only some arguments in some functions. Should we even have this? The type checker should catch an error if we pass the wrong type, so why was this added?

**Comment by AdamGleave** [comment]
Sorry I missed this issue until now and merged the PR before responding to your comments. Feel free to reopen if you feel there are issues unaddressed.

> (on [#472 (comment)](https://github.com/HumanCompatibleAI/imitation/pull/472#discussion_r927051214)_). Why is it particularly useful to check that this argument, which is typed as a tensor, is indeed a tensor? Does not seem consistent to randomly check the type of only some arguments in some functions. Should we even have this? The type checker should catch an error if we pass the wrong type, so why was this added?

I think `log_policy_act_prob` is not available for certain policies. E.g. Many Q-learning algorithms have a deterministic policy that's the argmax of the Q-function (modulo epsilon-greediness). So they're incompatible with AIRL, but work fine with GAIL that doesn't need `log_policy_act_prob`. We handle this by returning None [here](https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/algorithms/adversarial/common.py#L473) when the policy is incompatible.

So I think the original behavior of just checking it's non-None is reasonable, although we could make the error message more explanatory and self-documenting.

> If this is because the class must conform to a certain protocol, maybe we want to define the protocol for clarity? It feels quite silly otherwise.

It's a method inherited from `AdversarialTrainer`, so isn't the protocol in effect defined there?

**Comment by Rocamonde** [comment]
Hi Adam, that makes sense.

> 
> It's a method inherited from AdversarialTrainer , so isn't the protocol in
> effect defined there?
> 

You're right, that slipped my mind. Thanks for pointing it out.

Best wishes,

Juan
