### ISSUE TITLE
Fill in project description in docs

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#498]
- [x] Fill in the `what is imitation page'
- [ ] (Optional) Add FAQs to the FAQ page
- [x] Add greater detail to README.md table with implementations

**Comment by Rocamonde** [comment]
> I'm inclined to also move our tutorials above the algorithm descriptions?

I agree that this might be clearer to read. Below are some points related to this that I think we might want to think about:
1. Tutorial names on the sidebar are slightly too long and repetitive. 
2. The tutorials render the dedicated page for algorithms almost useless, because IIUC these pages just pull together a reduced version of the tutorial and the API (which is already in the API reference). I think we should move the code snippet to the docstrings, possibly reducing it to a minimum viable example; then this makes it available in the API reference. Then make the tutorial the default algo page with a link to the API reference.


Happy to make some of these tweaks, but as you've correctly labeled it might be a good first issue for incoming contributors.

**Comment by AdamGleave** [comment]
Dedicated algo pages also summarize what the algorithm does and link to the paper they're implementing, which is a useful version.

I do think trimming down the example code in the algos would be useful, right now it's quite verbose as lightly adapted from the tutorial as you say, but I'd be in favor of keeping the algo page and aiming to instead expand it over time (e.g. it's a good place to add gotchas, discussions of pros/cons of using this vs other algorithms, etc).

**Comment by Rocamonde** [comment]
That makes sense and is a good point. Then why not move the tutorial be within the algo page? Unless we plan to have tutorials for other things that aren't algorithms.

**Comment by AdamGleave** [comment]
Integrating tutorial as part of algo page could work. In terms of the user story I tend to think of tutorials as being something you work through when first working with imitation, whereas algo pages being more versatile including a reference function. But if we just have tables of contents for the algorithm that makes the tutorial easily discoverable (and skippable), then it could be fine.

**Comment by Rocamonde** [comment]
If we plan to have tutorials that are not exclusively themed around one per algo, and more themed around a story (e.g. https://reactjs.org/tutorial/tutorial.html or https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html), then I support having separate tutorial and algorithm pages. 

Even though I still think that if our API docs get quite good, we should have code examples, discussions, and references to papers there too, and the space that algo pages might occupy becomes more limited and less clear. I'm not too opinionated about this, but I do think that we should make the API docs as useful as possible and not just a spit-out of the method signature, that's not super useful and one can see it (arguably better) by reading the code.

**Comment by AdamGleave** [comment]
> If we plan to have tutorials that are perhaps not exclusively one per algo, and more like themed around a story, e.g. first steps / 10 min intro / "how algos X and Y can be used to accomplish [high-level goal]" (https://reactjs.org/tutorial/tutorial.html or https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html), then I support having separate tutorial and algorithm pages for the reasons you've mentioned.
I'd like us to move in that direction, but it's not something I have a concrete plan for.

> Even though I still think that if our API docs get quite good, we should have code examples, discussions, and references to papers there too, and the space that algo pages might occupy becomes more limited and less clear. I'm not too opinionated about this, but I do think that we should make the API docs as useful as possible and not just a spit-out of the method signature, that's not super useful and one can see it (arguably better) by reading the code.

Fair point -- I'd be fine just making the API docs more extensive, and adding them to the side-bar (so you don't have to dig through the API reference to find it).

**Comment by AdamGleave** [comment]
Fixed in #609
