### ISSUE TITLE
Fix test PyPI automation

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#500]
Currently we have a GitHub workflow that uploads to test PyPI on every commit; and to real PyPI on the release. The idea of the test PyPI automation is to check the automation is working and that the package is accepted by PyPI on each commit. In particular this'll catch things like `setup.py` depending on things not in PyPI.

However, this automation is sometimes failing because of version number conflicts. This is because we're automatically generating versions with `setuptools_scm`, which for pre-release appends a `.devN` number. This seems to be guessing the N based on how many commits relative to the last release. But a linear number N that's incremented can't handle there being multiple branches. Usually setuptools_scm handles this with a local scheme including things like a GitHub commit hash -- but test PyPI doesn't accept that, so we've disabled it with `no-local-version`.

I think we either need to remove the test PyPI automation (simplest, but loses some checks), or hack `setuptools_scm` to include the local scheme but in a way that PyPI accepts (e.g. change `-` to `_`).

I'm surprised there isn't a good general solution to this. Some relevant issues: https://github.com/pypa/setuptools_scm/issues/455 and https://github.com/pypa/setuptools_scm/issues/342

**Comment by Rocamonde** [comment]
I guess my first question would be, why are we using pre-release versions? We probably shouldn't do that if we can avoid it, as this makes it hard for other people to use our library (we're forcing them to use unstable software which might be incompatible with their code or other packages they use).

**Comment by AdamGleave** [comment]
I don't quite understand this question. This is for *test PyPI*, not production PyPI. No user will ever see these packages, unless they go out of their way to point pip at test PyPI. It's solely to test that the automated pip release workflow works correctly.

**Comment by Rocamonde** [comment]
Apologies, I thought the pre-release versions came from the dependencies, not from the package itself, as it also seemed surprising to me that there is not already a solution for this issue. I will investigate.

**Comment by Rocamonde** [comment]
Is there a way to check if the installer is being run for test pypi purposes or for regular pypi purposes? Because the benefit of this "bug" is that unversioned releases will never get published, which is actually a very important feature.

**Comment by Rocamonde** [comment]
Actually there's another problem with this, which is that any other version format is not PEP 440 compliant, so the wheel does not compile, which is a requirement for pyproject.toml-based projects. I don't think testpypi can be configured to allow local versions. 

Possible solutions: 

1. Remove
2. Convert git hash (hexadecimal) to a number, so that it is PEP 440 compliant (effectively using it as a build number). Seems like the best solution, but can also be obscure for new users to know where that number comes from.
3. Use some other way to generate a build number that is PEP 440 compliant, e.g. sequential. Perhaps more intuitive but seemingly much harder to implement.

**Comment by AdamGleave** [comment]
> I have a fix for this now, but is there a way to check if the installer is being run for test pypi purposes or for regular pypi purposes? Because the benefit of this "bug" is that unversioned releases will never get published, which is actually a very important feature. What is the current workflow for version tagging and release? (maybe we can set up the checks there)

We could just check an environment variable. But, the workflow would need to be changed for that, as right now we just build one wheel and then upload it to both test PyPI and (if tagged as a release) prod PyPI.

Building different wheels for each would make it a bit less of a reliable test (perhaps the prod wheel is broken in some way the test wheel is not?) but probably the least evil option if the only difference is in the versioning.

> Possible solutions:

2 seems like the best option IMO. 1 removing the local version I think is what we're doing now? The problem is it produces duplicate versions, so test PyPI uploads start failing. Sequential build numbering with 3 sounds hard given that people can be working on different Git branches, I guess you might be able to get some sequential ID from GitHub Actions, but sounds kinda fragile and then it'd do something different if run locally or in a separate CI system.

**Comment by Rocamonde** [comment]
Just submitted a PR #528 that fixes this by going for 2.

**Comment by Rocamonde** [comment]
So only regular PyPI is triggered if the commit is tagged as a release. That's good, that should fix the problem then, so nothing to worry about.
