### ISSUE TITLE
Fix loss mean v.s. loss sum in ensemble

### ISSUE THREAD

**Issue by levmckinney** [HumanCompatibleAI/imitation#503]
Switch reward ensembles over from taking the `loss.mean()` of all its members losses to the `loss.sum()` of its members losses so that gradients are not effectively scaled inversely proportional to the by the number of members.

**Comment by AdamGleave** [comment]
Good catch. Should be a one-line fix?

**Comment by levmckinney** [comment]
Just remembered it. @taufeeque9 had this fix in his pull request see https://github.com/HumanCompatibleAI/imitation/pull/482#discussion_r927201687

**Comment by levmckinney** [comment]
It looks like I did actually fix this https://github.com/HumanCompatibleAI/imitation/blob/c1a992a75b6ac9aa708b798a47ea327ca81150e7/src/imitation/algorithms/preference_comparisons.py#L975.
