### ISSUE TITLE
Improve bagging for ensemble training

### ISSUE THREAD

**Issue by levmckinney** [HumanCompatibleAI/imitation#530]
Is bagging the batch what we want to do for ensemble training. I think we should be sampling independent batches from the dataset for each ensemble member.

_Originally posted by @levmckinney in https://github.com/HumanCompatibleAI/imitation/pull/482#discussion_r948382938_

**Comment by AdamGleave** [comment]
@taufeeque9 you and Lev should figure out which one of you is going to work on this -- don't want you to both spend time on this.

**Comment by taufeeque9** [comment]
I can work on it if @levmckinney  hasn't started it yet. 

The plan is to use [`torch.utils.data.RandomSampler`](https://pytorch.org/docs/stable/data.html#torch.utils.data.RandomSampler) with `replacement=True` in the `_make_data_loader` function when preparing the `DataLoader`. We can further make mini-batches of the data from `RandomSampler` by using [`torch.utils.data.BatchSampler`](https://pytorch.org/docs/stable/data.html#torch.utils.data.BatchSampler).
