### ISSUE TITLE
Switch to using pathlib

### ISSUE THREAD

**Issue by levmckinney** [HumanCompatibleAI/imitation#531]
Why aren't we using Pathlib?

_Originally posted by @Rocamonde in https://github.com/HumanCompatibleAI/imitation/pull/529#discussion_r951410908_

**Comment by Rocamonde** [comment]
I'll prepare a PR for this as I've used Pathlib extensively, subject to other agreeing with this switch.

**Comment by AdamGleave** [comment]
We already use it in some places:

```python
find src/imitation -name '*.py' | xargs grep "import pathlib"
src/imitation/algorithms/dagger.py:import pathlib
src/imitation/data/types.py:import pathlib
src/imitation/util/sacred.py:import pathlib
src/imitation/policies/serialize.py:import pathlib
```

It's not a priority to me but happy to see us use it, I think it does make sense to switch.
