### ISSUE TITLE
Incompatible with ray 2.0.0.

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#533]
## Bug description
Due to the ray 2.0.0. release, code that uses ray is breaking. (to be expected in a major release). Currently #528 will pin the version to 1.x that we were using before, but a decision has to be made whether to upgrade to 2.0.0 (presumably desirable) and make the necessary changes (thus dropping 1.x. support?) or keep the pin for now.

## Steps to reproduce
Clone the repo and run the tests.

**Comment by AdamGleave** [comment]
I'd advocate for upgrading to Ray 2.0 -- we don't use Ray that extensively, so it should only require minor tweaks.
