### ISSUE TITLE
`ShapedRewardNet` has no effect when calling `predict_processed`

### ISSUE THREAD

**Issue by levmckinney** [HumanCompatibleAI/imitation#543]
## Bug description
Calling `predict_processed` on a `ShapedRewardNet` has no effect since it bypasses the shaping applied in the forward call.

## Steps to reproduce
Create a shaped reward network. Observe that the shaping function never gets called when calling the `predict_processed` method.

First mentioned by @dfilan in https://github.com/HumanCompatibleAI/imitation/pull/519#issuecomment-1231004118
> Turns out no potentials were being covered by tests, since the code was calling the predict_processed method of the ShapedRewardNets, which in turn called the base network's predict_processed, which called the base network's forward - not the ShapedRewardNet's forward. Should have a fix up in a few minutes.

**Comment by dfilan** [comment]
Fixed this in the CNN reward functions PR, but should probably make it its own PR. FYI my fix caused some tests to fail, which I think is not my fault but I'm not totally sure.

**Comment by dfilan** [comment]
Also my bad, it was `predict` not `predict_processed`.

**Comment by levmckinney** [comment]
> Also my bad, it was `predict` not `predict_processed`.

I think this bug should apply to both.

**Comment by dfilan** [comment]
Indeed - but it makes more sense for `ShapedRewardNet` to have a `predict` method than a `predict_processed` method.
