### ISSUE TITLE
Remove type ignore in replay_buffer_wrapper once new mypy version is released

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#552]
Remove the `#type: ignore[override]` (added in #534) on `policies/breply_buffer_wrapper.py` for the properties `pos()` and `full()` once https://github.com/python/mypy/pull/13475 is released into a new pypi version.

**Comment by ernestum** [comment]
Looks like this has been resolved with e99064a4a75ce61f0947c6b75506b5dddaae8aac .
