### ISSUE TITLE
Remove type ignore once DLR-RM/stable-baselines3#1027 is fixed

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#553]
Remove type: ignore[override] from `forward()` overrides in BaseModel subclasses once https://github.com/DLR-RM/stable-baselines3/issues/1027 is fixed.

**Comment by AdamGleave** [comment]
@Rocamonde: The upstream PR got merged, should we make this change? I think it's possible we actually already fixed most (all?) of these instances in another PR.

**Comment by Rocamonde** [comment]
Only one instance left as far as I could find, will remove it now and submit a PR.

**Comment by Rocamonde** [comment]
Submitted PR, which should close this issue.
