### ISSUE TITLE
train_rl.py ignores the `post_wrappers` config setting

### ISSUE THREAD

**Issue by dfilan** [HumanCompatibleAI/imitation#559]
## Bug description
When using the `train_rl` script, setting `post_wrappers` to add environment wrappers is a no-op: the script trains on the unwrapped environment. This is because the `train_rl` function ignores that config setting and sets `post_wrappers` to just contain a `RolloutInfoWrapper`.

## Steps to reproduce
Add a config like so to `config/train_rl.py`:
```
@train_rl_ex.named_config
def asteroids():
    common = dict(
        env_name="AsteroidsNoFrameskip-v4",
        post_wrappers=[
            lambda env, _: AtariWrapper(env, terminal_on_life_loss=False),
        ]
    )
```

Then run `python -m imitation.scripts.train_rl with asteroids common.fast train.fast rl.fast fast`.

**Comment by dfilan** [comment]
Update: looks like `post_wrappers` is only a config entry on a branch, not on master. So can't really say this is a bug.

**Comment by AdamGleave** [comment]
Fair enough -- seems like a reasonable feature to add though, so happy to see a PR for that!

**Comment by dfilan** [comment]
Yeah, current plan is to bundle this all in a `cnn_scripts` PR, to submit this week.
