### ISSUE TITLE
Fix mypy type erorrs in skipped files

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#573]
## Bug description
Some files are failing mypy type checks (but passing on pytype) and being skipped by `EXCLUDE_MYPY` in `.circleci/config.yml` introduced in https://github.com/HumanCompatibleAI/imitation/pull/534 We should fix these errors, by ignoring spurious errors and for true-positive errors refactoring the code or adding assert checks where appropriate.

## Steps to reproduce
Run `mypy` on the excluded files

**Comment by ianyfan** [comment]
I've had a look at the remaining excluded files, and I think I can open a PR tomorrow to fix most if not all of the remaining issues. (if no one else is actively working on this)
