### ISSUE TITLE
Type errors in `tests/algorithms/test_mce_irl.py`

### ISSUE THREAD

**Issue by dfilan** [HumanCompatibleAI/imitation#579]
On master, running `mypy tests/algorithms/test_mce_irl.py` yields:

```
tests/algorithms/test_mce_irl.py:10: error: Module "seals.diagnostics" has no attribute "random_trans"
tests/algorithms/test_mce_irl.py:119: error: Name "base_envs.TabularModelPOMDP" is not defined
tests/algorithms/test_mce_irl.py:409: error: Module has no attribute "ExposePOMDPStateWrapper"
Found 3 errors in 1 file (checked 1 source file)
```

I'm not sure how CI didn't catch this, but it seems good for this sort of thing to be ironed out before merging into master, so that people can use mypy as a pre-commit hook.

**Comment by dfilan** [comment]
My current plan is to deal with this once I finish testing the PR I'm currently working on (aka Euro!today).

**Comment by Rocamonde** [comment]
Did you merge master and reinstall your seals version? This totally looks like mypy is inspecting outdated seals files before we merged the "imitation to seals environment migration" PR

**Comment by dfilan** [comment]
Oops, indeed I forgot to reinstall seals after pulling master. After doing that, there's no more issues. Sorry for being a bit curt in OP.
