### ISSUE TITLE
Flaky DAgger tests under MacOs

### ISSUE THREAD

**Issue by ernestum** [HumanCompatibleAI/imitation#580]
## Bug description
When preparing the PR #569, the DAgger tests `test_trainer_makes_progress` became flaky under MacOS after some time. The commit 31169c3634fd8fb8b278a47a2586b24b2554ac46 fixed this by just training longer. However, this is highly suspicious. We would expect the performance of DAgger to be equally bad/flaky on all operating systems.

## Steps to reproduce
Decrease the number of iterations in the test again (revert 31169c3634fd8fb8b278a47a2586b24b2554ac46), commit and push to trigger the pipeline.
You can re-run the MacOS runner with SSH and install [`pytest-flakefinder`](https://github.com/dropbox/pytest-flakefinder) on the `test_trainer_makes_progress` test to verify that in some cases the test passes and in some cases it fails. For me it failed in 8/10 cases.

## Environment
- Operating system and version: MacOs

**Comment by AdamGleave** [comment]
I believe this has been fixed in the multiple flaky test PRs, but feel free to re-open if issue is observed again.
