### ISSUE TITLE
Remove type: ignore once evaluate_policy type annotation generalized

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#600]
Remove `# type: ignore[arg-type]` introduced in https://github.com/HumanCompatibleAI/imitation/pull/593/files#diff-648af1fe52e7f75f6ddc457b062fe9ee7b456d9358c493cef1a3547f5e87785b for `evaluate_policy` once https://github.com/DLR-RM/stable-baselines3/pull/1146 is merged

**Comment by AdamGleave** [comment]
https://github.com/DLR-RM/stable-baselines3/pull/1146 got merged so now we're just waiting on the next SB3 release

**Comment by ernestum** [comment]
@AdamGleave should I take care of the new SB3 release so we can get forward on this?

**Comment by AdamGleave** [comment]
If you can make a new SB3 release in <1 hour then go for it. Otherwise probably not worth it: this issue is just a nit, it could wait.

**Comment by ernestum** [comment]
@araffin made a new release for us so we can progress on this.
