### ISSUE TITLE
Typo in ActiveSelectionFragmenter

### ISSUE THREAD

**Issue by rk1a** [HumanCompatibleAI/imitation#611]
## Bug description
In this line https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/algorithms/preference_comparisons.py#L678 the default value should be "logit"

## Steps to reproduce
Creating `ActiveSelectionFragmenter` with default arguments raises a ValueError

**Comment by AdamGleave** [comment]
Doh. Do you mind making the one-line PR to fix this? :)
