### ISSUE TITLE
Improve `RuntimeWarning` check in `test_scripts:test_train_rl_double_normalization`

### ISSUE THREAD

**Issue by anshradh** [HumanCompatibleAI/imitation#614]
## Problem
The test checks for a RuntimeWarning when train_rl is called with normalization on an already normalized reward function, but doesn't actually check the message included in the warning.

## Solution
Test should also assert that the warning's message matches the warning we think it's hitting.

**Comment by AdamGleave** [comment]
Fixed in #615
