### ISSUE TITLE
AgentTrainer 

### ISSUE THREAD

**Issue by AbraGanz** [HumanCompatibleAI/imitation#620]
## Bug description
I'm trying to set up a simple example, just setting up the reward trainer, agent and agent trainer following [the example](https://imitation.readthedocs.io/en/latest/tutorials/5a_train_preference_comparisons_with_cnn.html) given in the readthedocs file.  When calling the AgentTrainer function an error occurs in the Atari wrapper.

I have slightly edited this code, since the AgentTrainer function originally also had the input 'rng=rng' however this triggered an error that the AgentTrainer got an unexpected keyword - rng - so I removed it, as I could not see anywhere in the AgentTrainer or TrajectoryGenerator code where it would expect it.

## Steps to reproduce
**Code Sample**

```
import torch as th
import gym
from gym.wrappers import TimeLimit
import numpy as np

from seals.util import AutoResetWrapper

from stable_baselines3 import PPO
from stable_baselines3.common.atari_wrappers import AtariWrapper
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.ppo import CnnPolicy

from imitation.algorithms import preference_comparisons
from imitation.policies.base import NormalizeFeaturesExtractor
from imitation.rewards.reward_nets import CnnRewardNet

device = th.device("cuda" if th.cuda.is_available() else "cpu")

rng = np.random.default_rng()

# Here we ensure that our environment has constant-length episodes by resetting
# it when done, and running until all timesteps have elapsed.
# For real training, you will want a much longer time limit than 100
def constant_length_asteroids(num_steps):
    atari_env = gym.make('AsteroidsNoFrameskip-v4')
    preprocessed_env = AtariWrapper(atari_env)
    endless_env = AutoResetWrapper(preprocessed_env)
    return TimeLimit(endless_env, max_episode_steps=num_steps)

venv = make_vec_env(constant_length_asteroids, env_kwargs={"num_steps": 100})
venv = VecFrameStack(venv, n_stack=4)

reward_net = CnnRewardNet(
    venv.observation_space,
    venv.action_space,
).to(device)

# Note that for trajectory encoding we use TotalFragmenter so as to get all possible fragments.
fragmenter = preference_comparisons.TotalFragmenter()
gatherer = preference_comparisons.SyntheticGatherer()
preference_model = preference_comparisons.PreferenceModel(reward_net)
reward_trainer = preference_comparisons.BasicRewardTrainer(
    preference_model=preference_model,
    loss=preference_comparisons.CrossEntropyRewardLoss(),
    epochs=3,
)

agent = PPO(
    policy=CnnPolicy,
    env=venv,
    seed=0,
    n_steps=16,  # To train on atari well, set this to 128
    batch_size=16,  # To train on atari well, set this to 256
    ent_coef=0.01,
    learning_rate=0.00025,
    n_epochs=4,
)

trajectory_generator = preference_comparisons.AgentTrainer(
    algorithm=agent,
    reward_fn=reward_net,
    venv=venv,
    exploration_frac=0.0
)
```

**Traceback:**

```
AttributeError                            Traceback (most recent call last)
Cell In [10], line 64
     47 reward_trainer = preference_comparisons.BasicRewardTrainer(
     48     preference_model=preference_model,
     49     loss=preference_comparisons.CrossEntropyRewardLoss(),
     50     epochs=3,
     51 )
     53 agent = PPO(
     54     policy=CnnPolicy,
     55     env=venv,
   (...)
     61     n_epochs=4,
     62 )
---> 64 trajectory_generator = preference_comparisons.AgentTrainer(
     65     algorithm=agent,
     66     reward_fn=reward_net,
     67     venv=venv,
     68     exploration_frac=0.0
     69 )
     71 # pref_comparisons = preference_comparisons.PreferenceComparisons(
     72 #     trajectory_generator,
     73 #     reward_net,
   (...)
     82 #     initial_epoch_multiplier=1,
     83 # )

File ~/Documents/PIBBSS/imitation/src/imitation/algorithms/preference_comparisons.py:177, in AgentTrainer.__init__(self, algorithm, reward_fn, venv, exploration_frac, switch_prob, random_prob, seed, custom_logger)
    167 # The BufferingWrapper records all trajectories, so we can return
    168 # them after training. This should come first (before the wrapper that
    169 # changes the reward function), so that we return the original environment
   (...)
    174 # SB3 may move the image-channel dimension in the observation space, making
    175 # `algorithm.get_env()` not match with `reward_fn`.
    176 self.buffering_wrapper = wrappers.BufferingWrapper(venv)
--> 177 self.venv = self.reward_venv_wrapper = reward_wrapper.RewardVecEnvWrapper(
    178     self.buffering_wrapper,
    179     reward_fn=self.reward_fn,
    180 )
    182 self.log_callback = self.reward_venv_wrapper.make_log_callback()
    184 self.algorithm.set_env(self.venv)

File ~/Documents/PIBBSS/imitation/src/imitation/rewards/reward_wrapper.py:70, in RewardVecEnvWrapper.__init__(self, venv, reward_fn, ep_history)
     68 self._old_obs = None
     69 self._actions = None
---> 70 self.reset()

File ~/Documents/PIBBSS/imitation/src/imitation/rewards/reward_wrapper.py:81, in RewardVecEnvWrapper.reset(self)
     80 def reset(self):
---> 81     self._old_obs = self.venv.reset()
     82     return self._old_obs

File ~/Documents/PIBBSS/imitation/src/imitation/data/wrappers.py:45, in BufferingWrapper.reset(self, **kwargs)
     43 self._init_reset = True
     44 self.n_transitions = 0
---> 45 obs = self.venv.reset(**kwargs)
     46 self._traj_accum = rollout.TrajectoryAccumulator()
     47 for i, ob in enumerate(obs):

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_frame_stack.py:58, in VecFrameStack.reset(self)
     54 def reset(self) -> Union[np.ndarray, Dict[str, np.ndarray]]:
     55     """
     56     Reset all environments
     57     """
---> 58     observation = self.venv.reset()  # pytype:disable=annotation-type-mismatch
     60     observation = self.stackedobs.reset(observation)
     61     return observation

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py:63, in DummyVecEnv.reset(self)
     61 def reset(self) -> VecEnvObs:
     62     for env_idx in range(self.num_envs):
---> 63         obs = self.envs[env_idx].reset()
     64         self._save_obs(env_idx, obs)
     65     return self._obs_from_buf()

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/stable_baselines3/common/monitor.py:83, in Monitor.reset(self, **kwargs)
     81         raise ValueError(f"Expected you to pass keyword argument {key} into reset")
     82     self.current_reset_info[key] = value
---> 83 return self.env.reset(**kwargs)

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/gym/wrappers/time_limit.py:27, in TimeLimit.reset(self, **kwargs)
     25 def reset(self, **kwargs):
     26     self._elapsed_steps = 0
---> 27     return self.env.reset(**kwargs)

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/gym/core.py:292, in Wrapper.reset(self, **kwargs)
    291 def reset(self, **kwargs):
--> 292     return self.env.reset(**kwargs)

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/gym/core.py:292, in Wrapper.reset(self, **kwargs)
    291 def reset(self, **kwargs):
--> 292     return self.env.reset(**kwargs)

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/gym/core.py:333, in RewardWrapper.reset(self, **kwargs)
    332 def reset(self, **kwargs):
--> 333     return self.env.reset(**kwargs)

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/gym/core.py:319, in ObservationWrapper.reset(self, **kwargs)
    318 def reset(self, **kwargs):
--> 319     observation = self.env.reset(**kwargs)
    320     return self.observation(observation)

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/stable_baselines3/common/atari_wrappers.py:59, in FireResetEnv.reset(self, **kwargs)
     58 def reset(self, **kwargs) -> np.ndarray:
---> 59     self.env.reset(**kwargs)
     60     obs, _, done, _ = self.env.step(1)
     61     if done:

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/stable_baselines3/common/atari_wrappers.py:106, in EpisodicLifeEnv.reset(self, **kwargs)
     97 """
     98 Calls the Gym environment reset, only when lives are exhausted.
     99 This way all states are still reachable even though lives are episodic,
   (...)
    103 :return: the first observation of the environment
    104 """
    105 if self.was_real_done:
--> 106     obs = self.env.reset(**kwargs)
    107 else:
    108     # no-op step to advance from terminal/lost life state
    109     obs, _, _, _ = self.env.step(0)

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/stable_baselines3/common/atari_wrappers.py:154, in MaxAndSkipEnv.reset(self, **kwargs)
    153 def reset(self, **kwargs) -> GymObs:
--> 154     return self.env.reset(**kwargs)

File ~/opt/anaconda3/envs/imitation/lib/python3.9/site-packages/stable_baselines3/common/atari_wrappers.py:36, in NoopResetEnv.reset(self, **kwargs)
     34     noops = self.override_num_noops
     35 else:
---> 36     noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)
     37 assert noops > 0
     38 obs = np.zeros(0)

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
```

## Environment
**Operating System**
macOS Monterey 12.1

**Environment**

absl-py==1.3.0
ale-py==0.7.5
anyio==3.6.2
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.1.0
attrs==22.1.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
cachetools==5.2.0
cffi==1.15.1
chai-sacred==0.8.3
charset-normalizer==2.1.1
cloudpickle==2.2.0
colorama==0.4.6
contourpy==1.0.6
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
docopt==0.6.2
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
fonttools==4.38.0
gitdb==4.0.9
GitPython==3.1.29
google-auth==2.14.0
google-auth-oauthlib==0.4.6
grpcio==1.50.0
gym==0.21.0
gym-legacy-toytext==0.0.5
idna==3.4
imitation==0.3.1
importlib-metadata==4.13.0
importlib-resources==5.10.0
ipykernel==6.17.0
ipython==8.6.0
ipython-genutils==0.2.0
ipywidgets==8.0.2
jedi==0.18.1
Jinja2==3.1.2
joblib==1.2.0
jsonpickle==2.2.0
jsonschema==4.17.0
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-server==1.21.0
jupyter_client==7.4.4
jupyter_core==4.11.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
kiwisolver==1.4.4
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
mistune==2.0.4
munch==2.5.0
nbclassic==0.4.8
nbclient==0.7.0
nbconvert==7.2.3
nbformat==5.7.0
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.23.4
oauthlib==3.2.2
packaging==21.3
pandas==1.5.1
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.3.0
pip==22.2.2
prometheus-client==0.15.0
prompt-toolkit==3.0.32
protobuf==3.19.6
psutil==5.9.3
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyglet==2.0.0
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
pytz==2022.6
pyzmq==24.0.1
qtconsole==5.4.0
QtPy==2.2.1
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==1.1.3
scipy==1.9.3
seals==0.1.5
Send2Trash==1.8.0
setuptools==65.5.0
setuptools-scm==7.0.5
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stable-baselines3==1.6.2
stack-data==0.6.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
terminado==0.17.0
threadpoolctl==3.1.0
tinycss2==1.2.1
tomli==2.0.1
torch==1.13.0
tornado==6.2
tqdm==4.64.1
traitlets==5.5.0
typing_extensions==4.4.0
urllib3==1.26.12
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.2
Werkzeug==2.2.2
wheel==0.37.1
widgetsnbextension==4.0.3
wrapt==1.14.1
zipp==3.10.0

**Comment by AdamGleave** [comment]
@taufeeque9 can you try and replicate this? It's failing in SB code so may be an upstream issue. From quick look it seems maybe  it's expecting `np_random` to be `np.random` (Which has `randint`) not a `Generator` (which has `integers`).

**Comment by taufeeque9** [comment]
The issue is that `imitation` and `stable_baselines3` both have the required dependency of [ `ale-py==0.7.4`](https://github.com/HumanCompatibleAI/imitation/blob/369ba0a678bea5c353a50e0befe11f5c70cf6166/setup.py#L19) and your environment has `ale-py==0.7.5` where the seeding mechanism has been [changed](https://github.com/mgbellemare/Arcade-Learning-Environment/releases/tag/v0.7.5). The quick fix would be to install the required version of the package: `pip install --upgrade ale-py==0.7.4`.

The longer-term solution will be to upgrade the dependency of `ale-py` for both `imitation` and `stable_baselines3`.  @AdamGleave if this sounds good, I can open a PR for both libraries.

As a side note, @AbraGanz you shouldn't get the unexpected keyword argument `rng` for `AgentTrainer` as it is a [required positional argument](https://github.com/HumanCompatibleAI/imitation/blob/369ba0a678bea5c353a50e0befe11f5c70cf6166/src/imitation/algorithms/preference_comparisons.py#L135).

**Comment by AdamGleave** [comment]
Thanks for looking into this @taufeeque9! We should upgrade `ale-py` long-term but I think it's probably best to hold off until we can upgrade `gym` as well, which is being worked on in https://github.com/DLR-RM/stable-baselines3/pull/780

**Comment by AbraGanz** [comment]
Thanks for your response to this, updating the package sorted it. 
(And you were quite right @taufeeque9, looks like I had an older version of the code, thanks for points that out)
