### ISSUE TITLE
Easy way to know mean episode return for expert models

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#63]
Maybe an text file inside the `expert_models.zip` (autogenerated in the S3 upload script #56 by `find outputs -name stdout | sort | xargs tail -n 15 | grep -E '==|ep_reward'`), or a new command in `scripts.policy_eval` that loops over the every model in `expert_models`.

**Comment by AdamGleave** [comment]
Seems useful. Maybe a CSV is better than my hacky text output so you can more easily import into other systems / visualize?

Having a loop in `scripts.policy_eval` seems confusing: it's designed to evaluate a single policy. Better to make a bash script with `parallel` or a Python script with `multiprocessing` that repeatedly calls `scripts.policy_eval`.

**Comment by shwang** [comment]
This is resolved, as our S3 data contains a `results.txt` with this information.
