### ISSUE TITLE
Is it possible to monitor training results during GAIL training?

### ISSUE THREAD

**Issue by rachitpras** [HumanCompatibleAI/imitation#634]
## Problem
Is it possible to monitor training performance during  GAIL training? Like the 'Monitor' feature in Stable baselines, which created the monitor.csv file? That helps in identifying how many steps are required to run the GAIL trainer.

Is there any other way of logging interim results during GAIL training? Like some callback? Its not clear from the example if something can be done like this.

**Comment by AdamGleave** [comment]
The training script `train_adversarial` already logs training statistics by default.
