### ISSUE TITLE
Question: Why GAIL trains generator before trains discriminator?

### ISSUE THREAD

**Issue by lbgitjp** [HumanCompatibleAI/imitation#635]
When i run the gail sample on this page: https://imitation.readthedocs.io/en/latest/algorithms/gail.html
i run into below code:
https://github.com/HumanCompatibleAI/imitation/blob/df2627446b7457758a0b09fa74a1fcb19403a236/src/imitation/algorithms/adversarial/common.py#L447-L452

i found in the for loop,
first it trains the generator at this line:
https://github.com/HumanCompatibleAI/imitation/blob/df2627446b7457758a0b09fa74a1fcb19403a236/src/imitation/algorithms/adversarial/common.py#L448

then it trains the discriminator at this line: https://github.com/HumanCompatibleAI/imitation/blob/df2627446b7457758a0b09fa74a1fcb19403a236/src/imitation/algorithms/adversarial/common.py#L452

then the for loop finished,
the generator didn't use the trained discriminator.

Why is it like this? shouldn't gail first train a discriminator, then use the discriminator to train the generator?

thanks!

**Comment by dfilan** [comment]
Those lines are inside a for loop, so they get repeated multiple times. For example, if `n_rounds` is 3, we train the generator, then the discriminator, then the generator again, then the discriminator again, then the generator a third time, then the discriminator a third time. Each time the generator is trained, it's trained using the discriminator: see lines 230 thru 237, where `venv_wrapped` is defined to be a vectorized environment using rewards generated by `reward_train` (the discriminator), `venv_train` is set to be equal to `venv_wrapped`, and `gen_algo` is set to train using `venv_train`.

**Comment by lbgitjp** [comment]
@dfilan thank you for your reply,
The n_rounds value is 1 on this gail example: https://imitation.readthedocs.io/en/latest/algorithms/gail.html.
when n_rounds  = 1,
**self.train_gen** train the generator use a **untrained** discriminator,
then **self.train_disc** train the discriminator use the expert samples, but this trained  discriminator  is not used,

So when n_rounds  = 1 the GAIL algorithm train nothing.
only when the n_rounds > 1, the trained discriminator can be used.
And the last round call of **self.train_disc** is meaningless, because the trained discriminator will never be used. it can't  improve the generator.

thanks!

**Comment by dfilan** [comment]
Ah - you're right that that's a bit strange. My one comment is that sometimes example code is run for a small number of timesteps so that it users can test it quickly. But it's possible we should be clearer about this issue with the GAIL example.

**Comment by AdamGleave** [comment]
@taufeeque9 has been looking at swapping these round. I think current results are that it doesn't affect performance much either way (for practical values of `n_rounds` -- you won't learn much either way if you only train for 1 round!) But we're going to do some more testing. Training discriminator first ends up being a bit tricky as we don't want to duplicate rollout collection for performance reasons.

**Comment by lbgitjp** [comment]
Thank you @dfilan and @AdamGleave.
i post this issue is just  to make sure I understand the algorithm correctly,
now i understand it, so the issue is cleared for me, 
so I will close this problem.

thanks!
