### ISSUE TITLE
best way to reproduce results (w Dagger) ?

### ISSUE THREAD

**Issue by pchalasani** [HumanCompatibleAI/imitation#643]
Each run with Dagger gives different results, and I am wondering what is the best/recommended way to freeze the random state when using Dagger? I freeze all possible seeds (torch, np, etc) but this module keeps giving different results on each run, most likely due to the `InteractiveTrajectoryCollector`. I even tried explicitly setting the seed in the `init` of this class, but the non-determinism persists. Any ideas would be appreciated. Thanks!

**Comment by pchalasani** [comment]
My envs are totally deterministic, so this non-determinism despite fixing all obvious seeds really stumped me for half a day. But I figured out this was due to the random path names for storing trajectories:

```
def make_unique_timestamp() -> str:
    """Timestamp, with random uuid added to avoid collisions."""
    ISO_TIMESTAMP = "%Y%m%d_%H%M%S"
    timestamp = datetime.datetime.now().strftime(ISO_TIMESTAMP)
    random_uuid = uuid.uuid4().hex[:6]
    return f"{timestamp}_{random_uuid}"
```
 I patched it in my own version by making these changes, in case it's useful for someone:

* turning off the uuid, and instead just generate sequential prefix when calling  `_save_dagger_demo`,
* there was another potential reproducibility risk involving `_get_demo_paths()` , where `listdir` may return file paths in some arbitrary non-deterministic order. Just to be safe, I changed this fn to return a sorted list of paths.

I'm really surprised this non-determinism didn't come up before. (Regarding the `uuid4`, I suppose one could fix it via some seed fixing plus other changes as suggested here https://stackoverflow.com/questions/41186818/how-to-generate-a-random-uuid-which-is-reproducible-with-a-seed-in-python , but I think it's just easier to avoid generating these random prefixes and just use sequential ones instead)


-

**Comment by AdamGleave** [comment]
Thanks for the report! @ernestum do you want to look into this issue and how best to fix it?

**Comment by ernestum** [comment]
Yes but I won't be able to look into it before next year.

**Comment by AdamGleave** [comment]
> Yes but I won't be able to look into it before next year.

OK, I don't think this is urgent.
