### ISSUE TITLE
GAIL benchmark ent_coeff

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#65]
GAIL Reacher experiments were paramertized by an entropy_coefficient. This is simply the `ent_coeff` arg in stable baselines PPO2 (h/t @qxcv).

![image](https://user-images.githubusercontent.com/1750835/62175196-8208fb80-b2f1-11e9-826c-9b5cef3e60d9.png)

- [ ] Add ent_coeff to gail_benchmarks_config.csv
- [ ] Update gail_benchmarks.sh to pass ent_coeff all the way to PPO2.

**Comment by AdamGleave** [comment]
This issue looks stale, should we close?
