### ISSUE TITLE
Add Gym/Gymnasium 0.26 support 

### ISSUE THREAD

**Issue by mertalbaba** [HumanCompatibleAI/imitation#666]
## Problem
The current package requires older version of Gym.

## Solution
Please provide support for current version of gym/gymnasium like stable-baselines3 did.

## Possible alternative solutions
Description of any alternative solutions or features you've considered.

**Comment by AdamGleave** [comment]
My understanding is stable-baselines3 doesn't have stable support for this yet -- it's still under review on https://github.com/DLR-RM/stable-baselines3/pull/780 Am I missing something?

Our current roadmap is to add support for this once SB3 merges it. We don't have bandwidth to maintain two parallel versions with our current dev team, although PRs are welcome ;)

**Comment by mertalbaba** [comment]
Yes, it is not stable right now. Thanks anyways :)

**Comment by levmckinney** [comment]
Reopening this issue now that stable baselines has merged support for Gymnasium into master https://github.com/DLR-RM/stable-baselines3/pull/1327. While they have not yet released stable baselines 2.0.0 it seems like this will happen quite soon.
