### ISSUE TITLE
Unneded nvidia/cuda dependencies bloat pipeline caches

### ISSUE THREAD

**Issue by ernestum** [HumanCompatibleAI/imitation#708]
## Problem
I just discovered that we spend 1m15s on just downloading the venv cache [in the pipeline](https://app.circleci.com/pipelines/github/HumanCompatibleAI/imitation/3443/workflows/f5d28e8c-6a0b-4852-804d-347f5f2a0d21/jobs/13011) 
Most of that cache is filled with nvidia/cuda dependencies, that are not needed. 

## Solution
We could reduce time/bandwidth usage by by installing a cpu-only version of pytorch in the pipeline.
It can be installed with:
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
```
More resources:
- https://pytorch.org/get-started/locally/
- https://stackoverflow.com/a/61605708

## Possible alternative solutions
None.

**Comment by AdamGleave** [comment]
Well spotted!
