### ISSUE TITLE
Gym dependency will not install

### ISSUE THREAD

**Issue by levmckinney** [HumanCompatibleAI/imitation#729]
## Bug description
When attempting to install the gym dependency I get the following error:
```
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

## Steps to reproduce
Attempt to install imitation from source with a setuptools version grater than 65 see https://github.com/openai/gym/issues/3176

## Environment
- Operating system and version: archlinux
- Python version: 3.8

## Mitigation
This can be mitigated by downgrading to `setuptools==65.5.0` as pointed out in https://github.com/openai/gym/issues/3176#issuecomment-1408598628.

**Comment by levmckinney** [comment]
It seems like the only long term solution here is to switch to gymnasium #666. Stablebaslines now uses gymnasium by default https://github.com/DLR-RM/stable-baselines3/pull/1327 and continuing to the unmaintained gym dependency is untenable long term.

**Comment by AdamGleave** [comment]
Closing in favor of #734
