### ISSUE TITLE
Implement Soft Q imitation learning (SQIL)

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#740]
## Problem
[Soft Q imitation learning (SQIL)](https://arxiv.org/pdf/1905.11108.pdf) is a simple imitation learning algorithm that claims to achieve similar performance to more complicated algorithms like GAIL and AIRL. Adding it to `imitation` would enable an independent replication of these results and facilitate others using it as a baseline in environments not studied in the original paper.

## Solution
This issues proposes implementing SQIL. The algorithm is pleasingly simple: just Q-learning with a reward of +1 when the action matches the demonstrated action in a demonstrated state, and 0 for all other behavior. It can therefore be implemented on top of existing Q-learning implementations such as SB3's DQN.

Ideally the solution would be modular: a wrapper around key components of underlying Q-learning algorithms. However, some copy-pasting and modification may be difficult to avoid.

The first author of SQIL's [implementation](https://github.com/rddy/sqil-atari/tree/master) may be a useful reference, although the code is a modified version of a course homework assignment implementing DQN so is a little difficult to disentangle.

**Comment by jas-ho** [comment]
@AdamGleave I created an issue for the generalization to other off-policy algos here: #767
