### ISSUE TITLE
At least some tests are accidentally stochastic

### ISSUE THREAD

**Issue by RedTachyon** [HumanCompatibleAI/imitation#741]
## Bug description
In a [recent CI run](https://app.circleci.com/pipelines/github/HumanCompatibleAI/imitation/3572/workflows/03bf9cfe-431a-47da-9c1e-a1543a2891e5/jobs/13800) for an unrelated change, it's failing on one of the tests. (`tests.algorithms.test_tabular_policy_randomness`)

From what I can tell, it's because we're not actually properly seeding the RNG:
https://github.com/HumanCompatibleAI/imitation/blob/09ca7b6b19b2770f0b0d35246edd76b3aa40c7de/tests/conftest.py#L46-L48

This means there's a low (but non-zero) chance of each CI run failing for no good reason, which is generally not a good thing to have.

## Steps to reproduce
Go through `test_tabular_policy_randomness` in a debugger twice, compare the value of `np.mean(actions)` -- it will (probably be different)

**Comment by AdamGleave** [comment]
Fixed in #742
