### ISSUE TITLE
Add tutorials for the common use cases of the CLI

### ISSUE THREAD

**Issue by ernestum** [HumanCompatibleAI/imitation#748]
Those include:

- training with new demonstrations,
- comparing to a baseline

**Comment by AdamGleave** [comment]
This should probably expand https://imitation.readthedocs.io/en/latest/getting-started/cli.html

**Comment by jas-ho** [comment]
@AdamGleave https://github.com/HumanCompatibleAI/imitation/pull/761 is ready for final review
