### ISSUE TITLE
Need to use sb3_contrib, gymnasium

### ISSUE THREAD

**Issue by roeslib** [HumanCompatibleAI/imitation#754]
Hello,

I need to use version 2.0.0 of stable_baselines3 and gymnasium. After referring to the following two posts

- [https://github.com/HumanCompatibleAI/seals/pull/72/files](url)
- [https://github.com/HumanCompatibleAI/imitation/pull/735](url)

I would like to know if it is sufficient to only change "gym" to "gymnasium" in your source code, or if there are other modifications required.

Any guidance or insights would be greatly appreciated.

Thank you!

**Comment by Curtis-Tang** [comment]
Did you resolve this issue? My idea is not enough as the step() in 2.0.0 needs "truncated".

**Comment by roeslib** [comment]
I am working on it right now. It seems to be working as I can see the metrics in the terminal. However, there are two issues that I am currently investigating:

1. The mask is not functioning correctly, and I'm trying to find the reason behind this issue.
2. The values of the train loss and value_loss are unusually high, around 10^4. I'm trying to identify the cause of this high value.

To ensure compatibility with sb3_contrib, I made some changes in the source code of the imitation gym, replacing references to gymnasium. Additionally, in my gym environment, I modified the step function as follows:

`return self.actual_state, reward, done,False, info  `

To create the vectorized environment, I am using make_vec_env from the imitation library. In the file imitation.algorithm.adversarial.airl.py, I added the policy from sb3_contrib at line 8.

Please let me know if your mask works for you and also if you can tell me the values of value_loss it would be very helpful.

**Comment by Curtis-Tang** [comment]
Does your gymnasium env works fine with any algorithm in imitation? Did you trying to apply maskable PPO?

**Comment by roeslib** [comment]
My gymnasium works fine, my issue is with MaskablePPO and the policy MaskableActorCriticCnn, the mask is not working, and the value_loss is high. How were your results? Did you have similar issues as me?

**Comment by Curtis-Tang** [comment]
My gymnasium works fine with SB3 but not with imitation. I'm trying to use BC or any other imitation algorithm but no success for now. I will definitely work with Maskable PPO later.

**Comment by roeslib** [comment]
Which issues do you have? Could you please share your errors?

**Comment by roeslib** [comment]
ah I see, you need to install the sb3 1.7.0 version. [https://github.com/HumanCompatibleAI/imitation/pull/738](url)

**Comment by roeslib** [comment]
Sorry I am not familiar with that error.

**Comment by roeslib** [comment]
Sorry I am not familiar with that error.
