### ISSUE TITLE
"'Box' object has no attribute 'is_np_flattenable'"

### ISSUE THREAD

**Issue by H-Y-Zhu** [HumanCompatibleAI/imitation#757]
## Bug description
I got a bug "'Box' object has no attribute 'is_np_flattenable'" when running the Python Interface Quickstart code. Is it due to the version comparability between Gym, gymnasium, imitation? Thanks
## Steps to reproduce
Code or a description of how to reproduce the bug.

Training a expert.
Sampling expert transitions.
Traceback (most recent call last):
  File "/home/zhy/Data2TB/Reinforcement_Learning/test.py", line 51, in <module>
    bc_trainer = bc.BC(
  File "/home/zhy/Data2TB/miniconda3/envs/Reinforcement_Learning/lib/python3.10/site-packages/imitation/algorithms/bc.py", line 328, in __init__
    policy = policy_base.FeedForward32Policy(
  File "/home/zhy/Data2TB/miniconda3/envs/Reinforcement_Learning/lib/python3.10/site-packages/imitation/policies/base.py", line 72, in __init__
    super().__init__(*args, **kwargs, net_arch=[32, 32])
  File "/home/zhy/Data2TB/miniconda3/envs/Reinforcement_Learning/lib/python3.10/site-packages/stable_baselines3/common/policies.py", line 481, in __init__
    self.features_extractor = self.make_features_extractor()
  File "/home/zhy/Data2TB/miniconda3/envs/Reinforcement_Learning/lib/python3.10/site-packages/stable_baselines3/common/policies.py", line 120, in make_features_extractor
    return self.features_extractor_class(self.observation_space, **self.features_extractor_kwargs)
  File "/home/zhy/Data2TB/miniconda3/envs/Reinforcement_Learning/lib/python3.10/site-packages/stable_baselines3/common/torch_layers.py", line 41, in __init__
    super().__init__(observation_space, get_flattened_obs_dim(observation_space))
  File "/home/zhy/Data2TB/miniconda3/envs/Reinforcement_Learning/lib/python3.10/site-packages/stable_baselines3/common/preprocessing.py", line 185, in get_flattened_obs_dim
    return spaces.utils.flatdim(observation_space)
  File "/home/zhy/Data2TB/miniconda3/envs/Reinforcement_Learning/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/zhy/Data2TB/miniconda3/envs/Reinforcement_Learning/lib/python3.10/site-packages/gymnasium/spaces/utils.py", line 53, in flatdim
    if space.is_np_flattenable is False:
AttributeError: 'Box' object has no attribute 'is_np_flattenable'

The code of Python Interface Quickstart code (https://imitation.readthedocs.io/en/latest/getting-started/first_steps.html) is as below:
"""This is a simple example demonstrating how to clone the behavior of an expert.

Refer to the jupyter notebooks for more detailed examples of how to use the algorithms.

`  
  import gym
  import numpy as np
  from stable_baselines3 import PPO
  from stable_baselines3.common.evaluation import evaluate_policy
  from stable_baselines3.common.vec_env import DummyVecEnv
  from stable_baselines3.ppo import MlpPolicy
  
  from imitation.algorithms import bc
  from imitation.data import rollout
  from imitation.data.wrappers import RolloutInfoWrapper
  
  env = gym.make("CartPole-v1")
  rng = np.random.default_rng(0)
  
  
  def train_expert():
      print("Training a expert.")
      expert = PPO(
          policy=MlpPolicy,
          env=env,
          seed=0,
          batch_size=64,
          ent_coef=0.0,
          learning_rate=0.0003,
          n_epochs=10,
          n_steps=64,
      )
      expert.learn(100)  # Note: change this to 100000 to train a decent expert.
      return expert
  
  
  def sample_expert_transitions():
      expert = train_expert()
  
      print("Sampling expert transitions.")
      rollouts = rollout.rollout(
          expert,
          DummyVecEnv([lambda: RolloutInfoWrapper(env)]),
          rollout.make_sample_until(min_timesteps=None, min_episodes=50),
          rng=rng,
      )
      return rollout.flatten_trajectories(rollouts)
  
  
  transitions = sample_expert_transitions()
  bc_trainer = bc.BC(
      observation_space=env.observation_space,
      action_space=env.action_space,
      demonstrations=transitions,
      rng=rng,
  )
  
  reward, _ = evaluate_policy(
      bc_trainer.policy,  # type: ignore[arg-type]
      env,
      n_eval_episodes=3,
      render=True,
  )
  print(f"Reward before training: {reward}")
  
  print("Training a policy using Behavior Cloning")
  bc_trainer.train(n_epochs=1)
  
  reward, _ = evaluate_policy(
      bc_trainer.policy,  # type: ignore[arg-type]
      env,
      n_eval_episodes=3,
      render=True,
  )
  print(f"Reward after training: {reward}")
`
## Environment
- Operating system and version: Ubuntu 20.04.6 LTS
- Python version: 3.10
- Output of `pip freeze --all`:
- absl-py==1.4.0
actionlib==1.13.2
aiosignal==1.3.1
ale-py==0.7.4
angles==1.9.13
anyio==3.7.1
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.2.1
attrs==22.2.0
AutoROM==0.4.2
AutoROM.accept-rom-license==0.6.1
backcall==0.2.0
beautifulsoup4==4.12.2
black==22.6.0
bleach==6.0.0
bondpy==1.8.6
brotlipy==0.7.0
cachetools==5.3.1
camera-calibration==1.16.0
camera-calibration-parsers==1.12.0
catkin==0.8.10
certifi @ file:///croot/certifi_1683875369620/work/certifi
cffi @ file:///croot/cffi_1670423208954/work
cfgv==3.3.1
chai-sacred==0.8.3
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.0.4
cloudpickle==2.2.1
codecov==2.1.13
codespell==2.1.0
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.1.0
controller-manager==0.19.5
controller-manager-msgs==0.19.5
coverage==6.4.4
cryptography @ file:///croot/cryptography_1686613057838/work
cv-bridge==1.16.1
cycler==0.11.0
darglint==1.8.1
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
diagnostic-analysis==1.11.0
diagnostic-common-diagnostics==1.11.0
diagnostic-updater==1.11.0
dill==0.3.6
distlib==0.3.7
docker-pycreds==0.4.0
docopt==0.6.2
dynamic-reconfigure==1.7.3
exceptiongroup==1.1.2
execnet==2.0.2
executing==1.2.0
Farama-Notifications==0.0.4
fastjsonschema==2.17.1
filelock==3.7.1
flake8==4.0.1
flake8-blind-except==0.2.1
flake8-builtins==1.5.3
flake8-commas==2.1.0
flake8-debugger==4.1.2
flake8-docstrings==1.6.0
flake8-isort==4.1.2.post0
fonttools==4.41.0
frozenlist==1.4.0
fsspec==2023.6.0
gazebo_plugins==2.9.2
gazebo_ros==2.9.2
gencpp==0.6.5
geneus==3.0.0
genlisp==0.4.18
genmsg==0.5.16
gennodejs==2.0.2
genpy==0.6.15
getch==1.0
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==0.4.6
grpcio==1.43.0
gym==0.21.0
gymnasium==0.28.1
huggingface-hub==0.16.4
huggingface-sb3==2.2.5
humanfriendly==10.0
hypothesis==6.54.6
identify==2.5.24
idna @ file:///croot/idna_1666125576474/work
image-geometry==1.16.1
imitation==0.3.2
importlab==0.8
importlib-resources==6.0.0
iniconfig==2.0.0
interactive-markers==1.12.0
ipykernel==6.15.3
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==8.0.7
isort==5.12.0
jax-jumpy==1.0.0
jedi==0.18.2
Jinja2==3.1.2
joblib==1.3.1
joint-state-publisher==1.15.1
joint-state-publisher-gui==1.15.1
jsonpickle==3.0.1
jsonschema==4.18.3
jsonschema-specifications==2023.6.1
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.2
jupyter-server==1.24.0
jupyter-server-mathjax==0.2.6
jupyter_core==5.3.1
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
kiwisolver==1.4.4
laser_geometry==1.6.7
libcst==1.0.1
lxml==4.9.3
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.0.3
matplotlib-inline==0.1.6
mccabe==0.6.1
mdurl==0.1.2
message-filters==1.15.14
mistune==3.0.1
mkl-fft==1.3.6
mkl-random @ file:///work/mkl/mkl_random_1682950433854/work
mkl-service==2.4.0
moveit-core==1.1.10
msgpack==1.0.5
munch==2.5.0
mypy==0.991
mypy-extensions==1.0.0
nbclassic==1.0.0
nbclient==0.5.13
nbconvert==7.7.0
nbdime==3.2.1
nbformat==5.9.1
nest-asyncio==1.5.6
networkx==2.8.3
ninja==1.11.1
nodeenv==1.8.0
notebook==6.5.4
notebook_shim==0.2.3
numpy @ file:///croot/numpy_and_numpy_base_1687466208449/work
oauthlib==3.2.2
opencv-python==4.8.0.74
packaging==23.1
pandas==1.4.4
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.11.1
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
pip==23.1.2
platformdirs==3.9.1
pluggy==1.2.0
pre-commit==3.3.3
prometheus-client==0.17.1
promise==2.3
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.7.0
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py-cpuinfo==9.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycodestyle==2.8.0
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydocstyle==6.3.0
pydot==1.4.2
pyflakes==2.4.0
pygame==2.5.0
pyglet==1.5.27
Pygments==2.15.1
pyOpenSSL @ file:///croot/pyopenssl_1677607685877/work
pyparsing==3.0.9
Pyro4==4.82
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
pytest==7.1.3
pytest-cov==3.0.0
pytest-forked==1.6.0
pytest-xdist==2.5.0
pytest_notebook==0.8.0
python-dateutil==2.8.2
python-qt-binding==0.4.4
pytype==2022.7.26
pytz==2023.3
PyYAML==6.0
pyzmq==25.1.0
qt-dotgraph==0.4.2
qt-gui==0.4.2
qt-gui-cpp==0.4.2
qt-gui-py-common==0.4.2
qtconsole==5.4.3
QtPy==2.3.1
ray==2.0.1
referencing==0.29.1
requests @ file:///croot/requests_1682607517574/work
requests-oauthlib==1.3.1
resource_retriever==1.12.7
rich==13.4.2
rosbag==1.15.14
rosboost-cfg==1.15.8
rosclean==1.15.8
roscreate==1.15.8
rosgraph==1.15.14
roslaunch==1.15.14
roslib==1.15.8
roslint==0.12.0
roslz4==1.15.14
rosmake==1.15.8
rosmaster==1.15.14
rosmsg==1.15.14
rosnode==1.15.14
rosparam==1.15.14
rospy==1.15.14
rosservice==1.15.14
rostest==1.15.14
rostopic==1.15.14
rosunit==1.15.8
roswtf==1.15.14
rpds-py==0.8.11
rqt-moveit==0.5.10
rqt-reconfigure==0.5.5
rqt-robot-dashboard==0.5.8
rqt-robot-monitor==0.5.14
rqt-rviz==0.7.0
rqt_action==0.4.9
rqt_bag==0.5.1
rqt_bag_plugins==0.5.1
rqt_console==0.4.11
rqt_dep==0.4.12
rqt_graph==0.4.14
rqt_gui==0.5.3
rqt_gui_py==0.5.3
rqt_image_view==0.4.16
rqt_joint_trajectory_controller==0.20.0
rqt_launch==0.4.9
rqt_logger_level==0.4.11
rqt_msg==0.4.10
rqt_nav_view==0.5.7
rqt_plot==0.4.13
rqt_pose_view==0.5.11
rqt_publisher==0.4.10
rqt_py_common==0.5.3
rqt_py_console==0.4.10
rqt_robot_steering==0.5.12
rqt_runtime_monitor==0.5.9
rqt_service_caller==0.4.10
rqt_shell==0.4.11
rqt_srv==0.4.9
rqt_tf_tree==0.6.3
rqt_top==0.4.10
rqt_topic==0.4.13
rqt_web==0.4.10
rsa==4.9
rviz==1.14.19
scikit-learn==1.3.0
scipy==1.9.3
seals==0.1.5
Send2Trash==1.8.2
sensor-msgs==1.13.1
sentry-sdk==1.28.1
serpent==1.41
setproctitle==1.3.2
setuptools==63.2.0
setuptools-scm==7.0.5
Shimmy==0.2.1
shortuuid==1.0.11
six==1.16.0
smach==2.5.0
smach-ros==2.5.0
smclib==1.8.6
smmap==5.0.0
sniffio==1.3.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.4.1
srdfdom==0.6.3
stable-baselines3==2.0.0
stack-data==0.6.2
tabulate==0.9.0
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.6
terminado==0.17.1
tf==1.13.2
tf-conversions==1.13.2
tf2-geometry-msgs==0.7.5
tf2-kdl==0.7.5
tf2-py==0.7.5
tf2-ros==0.7.5
threadpoolctl==3.2.0
tinycss2==1.2.1
tokenize-rt==5.1.0
toml==0.10.2
tomli==2.0.1
topic-tools==1.15.14
torch==1.13.1
torchaudio==0.13.1
torchvision==0.14.1
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
typing==3.7.4.3
typing-inspect==0.9.0
typing_extensions @ file:///croot/typing_extensions_1686601443660/work
tzdata==2023.3
urdfdom-py==0.4.6
urllib3 @ file:///croot/urllib3_1686163155763/work
virtualenv==20.21.1
wandb==0.12.21
wasabi==1.1.2
wcwidth==0.2.6
webencodings==0.5.1
websocket-client==1.6.1
Werkzeug==2.3.6
wheel==0.38.4
widgetsnbextension==4.0.8
wrapt==1.15.0
xacro==1.14.13

**Comment by RedTachyon** [comment]
SB3==2.0.0 uses gymnasium, not gym

**Comment by H-Y-Zhu** [comment]
> SB3==2.0.0 uses gymnasium, not gym

Thanks for the reply. I am also confused on this because the tutorial example code in https://imitation.readthedocs.io/en/latest/getting-started/first_steps.html use import gym instead of import gymnasium as gym.
