### ISSUE TITLE
prob_true_act > 1 with PPO and BC?

### ISSUE THREAD

**Issue by ThomasRochefortB** [HumanCompatibleAI/imitation#762]
Quick question here:

Is it theoretically possible to obtain a value for prob_true_act >1 when training a BC algorithm using a PPO learner? For me it makes no sense at all. I am working on a reproduction script.
![image](https://github.com/HumanCompatibleAI/imitation/assets/47933584/368aabdb-4239-4995-bd3e-c72bdef5d330)

**Comment by ernestum** [comment]
Hi @ThomasRochefortB. Thanks for the bug report. Feel free to re-open this issue when you have a script to reproduce the issue.

**Comment by Ivan-267** [comment]
Hello, I ran into a similar issue, I wonder if this thread can help to give an explanation: https://github.com/pytorch/pytorch/issues/7637
