### ISSUE TITLE
Generalize SQIL to work with other off-policy algos

### ISSUE THREAD

**Issue by jas-ho** [HumanCompatibleAI/imitation#767]
## Problem
The current implementation of SQIL (PR: #744 , issue: #740 ) only works with DQN while the original paper also used soft-actor-critic and soft Q-learning. 

It would be great to have support in SQIL for, at least, SAC and, ideally, any off-policy algorithm supported in SB3.

## Solution
Generalize the SQIL constructor to allow instantiation of other off-policy algos in place of DQN.

**Comment by AdamGleave** [comment]
Yes, let's add this. We should also do some basic benchmarking of SQIL with these new algorithms, and ideally try to replicate the results of the SQIL paper.

**Comment by AdamGleave** [comment]
Fixed in #778
