### ISSUE TITLE
Observation space not supported when getting expert trajectories in tutorial 7

### ISSUE THREAD

**Issue by camberg23** [HumanCompatibleAI/imitation#788]
## Bug description
Hi, I am trying to go through the tutorials (specifically 7 with Pendulum-v1 expert), but when I try to collect the expert data, I continue to get a NotImplementedError: Box([-1. -1. -8.], [1. 1. 8.], (3,), float32) observation space is not supported. I also tried loading in the CartPole-v1 expert and got the same issue. 

I got this error both when pypi installing and installing from source—I tried both ways.

The strange part is that I can confirm the notebook was working last week following the identical download, which makes me wonder if the [new commit](https://huggingface.co/HumanCompatibleAI/ppo-CartPole-v1/tree/main) to HuggingFace is what is causing this. Thanks in advance for the help!

## Steps to reproduce
Tutorial 7 (kernel density) installed from source.

## Environment
absl-py==2.0.0
aiohttp==3.8.5
aiosignal==1.3.1
alabaster==0.7.13
ale-py==0.7.4
anyio==3.7.1
appnope==0.1.3
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.4.0
async-lru==2.0.4
async-timeout==4.0.3
attrs==22.2.0
autopep8==1.6.0
AutoROM==0.6.1
AutoROM.accept-rom-license==0.6.1
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
black==22.6.0
bleach==6.0.0
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
cfgv==3.4.0
charset-normalizer==3.2.0
click==8.0.4
cloudpickle==2.2.1
codecov==2.1.13
codespell==2.1.0
colorama==0.4.6
comm==0.1.4
contourpy==1.1.1
coverage==6.4.4
cycler==0.11.0
darglint==1.8.1
datasets==2.14.5
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.7
distlib==0.3.7
docker-pycreds==0.4.0
docopt==0.6.2
docutils==0.17.1
exceptiongroup==1.1.3
execnet==2.0.2
executing==1.2.0
Farama-Notifications==0.0.4
fastjsonschema==2.18.0
filelock==3.7.1
flake8==4.0.1
flake8-blind-except==0.2.1
flake8-builtins==1.5.3
flake8-commas==2.1.0
flake8-debugger==4.1.2
flake8-docstrings==1.6.0
flake8-isort==4.1.2.post0
fonttools==4.42.1
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2023.6.0
furo==2022.6.21
gitdb==4.0.10
GitPython==3.1.36
google-auth==2.23.0
google-auth-oauthlib==0.4.6
grpcio==1.43.0
gym==0.26.0
gym-notices==0.0.8
gymnasium==0.29.1
huggingface-hub==0.17.2
huggingface-sb3==2.3.1
hypothesis==6.54.6
identify==2.5.29
idna==3.4
imagesize==1.4.1
-e git+http://github.com/HumanCompatibleAI/imitation@885beff6dd52b24209bfa8627b202176750aa1c3#egg=imitation
importlab==0.8
importlib-metadata==4.13.0
importlib-resources==6.0.1
iniconfig==2.0.0
ipdb==0.13.13
ipykernel==6.15.3
ipython==8.15.0
ipython-genutils==0.2.0
ipywidgets==8.1.1
isoduration==20.11.0
isort==5.12.0
jedi==0.19.0
Jinja2==3.1.2
joblib==1.3.2
json5==0.9.14
jsonpickle==3.0.2
jsonpointer==2.4
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-cache==0.5.0
jupyter-client==6.1.12
jupyter-console==6.4.2
jupyter-core==5.3.1
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter-server==1.24.0
jupyter-server-mathjax==0.2.6
jupyter-server-terminals==0.4.4
jupyterlab==4.0.6
jupyterlab-pygments==0.2.2
jupyterlab-server==2.25.0
jupyterlab-widgets==3.0.9
kiwisolver==1.4.5
libcst==1.0.1
livereload==2.6.3
Markdown==3.4.4
markdown-it-py==2.2.0
MarkupSafe==2.1.3
matplotlib==3.8.0
matplotlib-inline==0.1.6
mccabe==0.6.1
mdit-py-plugins==0.3.5
mdurl==0.1.2
mistune==3.0.1
mpmath==1.3.0
msgpack==1.0.5
multidict==6.0.4
multiprocess==0.70.15
munch==2.5.0
mypy==0.991
mypy-extensions==1.0.0
myst-nb==0.16.0
myst-parser==0.18.1
nbclassic==1.0.0
nbclient==0.5.13
nbconvert==7.8.0
nbdime==3.2.1
nbformat==5.9.2
nest-asyncio==1.5.8
networkx==2.8.3
ninja==1.11.1
nodeenv==1.8.0
notebook==6.5.6
notebook-shim==0.2.3
numpy==1.25.2
oauthlib==3.2.2
opencv-python==4.8.0.76
overrides==7.4.0
packaging==23.1
pandas==1.4.4
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.11.2
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.1
pip==21.0
platformdirs==3.10.0
pluggy==1.3.0
pockets==0.9.1
pre-commit==3.4.0
prometheus-client==0.17.1
promise==2.3
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py-cpuinfo==9.0.0
pyarrow==13.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycodestyle==2.8.0
pycparser==2.21
pydocstyle==6.3.0
pydot==1.4.2
pyflakes==2.4.0
pyglet==1.5.27
Pygments==2.16.1
pyparsing==3.1.1
pytest==7.1.3
pytest-cov==3.0.0
pytest-forked==1.6.0
pytest-notebook==0.8.0
pytest-xdist==2.5.0
python-dateutil==2.8.2
python-json-logger==2.0.7
pytype==2022.7.26
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==24.0.1
qtconsole==5.4.4
QtPy==2.4.0
ray==2.0.1
referencing==0.30.2
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.5.3
rpds-py==0.10.3
rsa==4.9
sacred==0.8.4
scikit-learn==1.3.0
scipy==1.9.3
seals==0.1.5
Send2Trash==1.8.2
sentry-sdk==1.31.0
setproctitle==1.3.2
setuptools==65.5.0
setuptools-scm==7.0.5
shortuuid==1.0.11
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.5
Sphinx==5.1.1
sphinx-autobuild==2021.3.14
sphinx-autodoc-typehints==1.19.2
sphinx-basic-ng==1.0.0b2
sphinx-copybutton==0.5.0
sphinx-github-changelog==1.2.1
sphinx-rtd-theme==1.0.0
sphinx-togglebutton==0.3.2
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-napoleon==0.7
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
SQLAlchemy==1.4.49
stable-baselines3==1.7.0
stack-data==0.6.2
sympy==1.12
tabulate==0.9.0
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.6.2.2
terminado==0.17.1
threadpoolctl==3.2.0
tinycss2==1.2.1
tokenize-rt==5.2.0
toml==0.10.2
tomli==2.0.1
torch==2.0.1
tornado==6.3.3
tqdm==4.66.1
traitlets==5.10.0
typing-extensions==4.8.0
typing-inspect==0.9.0
uri-template==1.3.0
urllib3==1.26.16
virtualenv==20.21.1
wandb==0.12.21
wasabi==1.1.2
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.3
werkzeug==2.3.7
wheel==0.38.0
widgetsnbextension==4.0.9
wrapt==1.15.0
xxhash==3.3.0
yarl==1.9.2
zipp==3.17.0

**Comment by yojul** [comment]
Hi, I had the same error with a custom gym environment. Looking at your environment, it seems that you have both Gym and Gymnasium installed. 
I think that Imitation library (as well as stable-baselines3 v1..8.0) only works with Gym spaces.
In my case, I had to make sure that both Observation and Action spaces were defined as Gym objects (and not Gymnasium).

Hope it will help !

**Comment by cronopioelectronico** [comment]
Hi, 

Same problem for me when trying this https://github.com/HumanCompatibleAI/imitation/blob/master/examples/quickstart.py

This is how I solved it:

In env = make_vec_env
instead of "seals:seals/CartPole-v0" use "seals:CartPole-v1"  (different syntax, not just version)

Change load_policy by the following:
 expert = load_policy(
        'ppo',
        path='ppo-CartPole-v1.zip',
        venv=env,
    )

Download this file https://huggingface.co/sb3/ppo-CartPole-v1/blob/main/ppo-CartPole-v1.zip  (from https://huggingface.co/sb3/ppo-CartPole-v1/tree/main) and place it in the same folder as the script (or otherwise change the previous path option)

I had also to turn all the render options of the two evaluate_policy calls to False, but that may not be necessary.

**Comment by ernestum** [comment]
Note that `imitation` now only supports `gymnasium` and not `gym`. This should be fixed in version 1.0.0.
