### ISSUE TITLE
Mismatch between Tutorial doc and the actual jupyter notebook

### ISSUE THREAD

**Issue by ZiyueWang25** [HumanCompatibleAI/imitation#790]
## Bug description
The [tutorial](https://imitation.readthedocs.io/en/latest/tutorials/3_train_gail.html) "Train an Agent using Generative Adversarial Imitation Learning" doesn't match [the actual jupyter notebook](https://github.com/HumanCompatibleAI/imitation/blob/master/docs/tutorials/3_train_gail.ipynb) and it seems like it should be updated.

This also happens for other tutorials as well.

**Comment by ernestum** [comment]
This is probably because some jupyter notebook jobs silently failed as described in #799. Should be fixed by #803
