### ISSUE TITLE
DAgger Demo Code not working

### ISSUE THREAD

**Issue by nil123532** [HumanCompatibleAI/imitation#814]
## Bug description
Description of what the bug is.
Error code saying that the Gym Environment is invalid.

## Steps to reproduce
Code or a description of how to reproduce the bug.
`env = make_vec_env(
    "seals:seals/CartPole-v0",
    rng=np.random.default_rng(),
    n_envs=1,
)` running this block of code gets me this error:

`gym.error.DeprecatedEnv: Env seals/CartPole-v0 not found (valid versions include ['CartPole-v0', 'CartPole-v1'])`

## Environment
- Operating system and version: 
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

- Python version: Python 3.10.12

- Output of `pip freeze --all`:
absl-py==2.0.0
aiohttp==3.8.6
aiosignal==1.3.1
ale-py==0.7.4
alembic==1.12.0
anyio==3.7.1
apturl==0.5.2
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
asttokens==2.4.0
async-timeout==4.0.3
attrs==22.2.0
AutoROM==0.6.1
AutoROM.accept-rom-license==0.6.1
backcall==0.2.0
bcrypt==3.2.0
beautifulsoup4==4.12.2
black==22.6.0
bleach==6.1.0
blinker==1.4
Brlapi==0.8.3
cachetools==5.3.1
certifi==2020.6.20
cffi==1.16.0
cfgv==3.4.0
chardet==4.0.0
charset-normalizer==3.3.1
click==8.0.3
cloudpickle==3.0.0
codecov==2.1.13
codespell==2.1.0
colorama==0.4.4
colorlog==6.7.0
comm==0.1.4
command-not-found==0.3
contourpy==1.1.1
coverage==6.4.4
cryptography==3.4.8
cupshelpers==1.0
cycler==0.12.1
darglint==1.8.1
datasets==2.14.5
dbus-python==1.2.18
debugpy==1.8.0
decorator==5.1.1
defer==1.0.6
defusedxml==0.7.1
dill==0.3.7
distlib==0.3.7
distro==1.7.0
distro-info==1.1+ubuntu0.1
docker-pycreds==0.4.0
docopt==0.6.2
duplicity==0.8.21
exceptiongroup==1.1.3
execnet==2.0.2
executing==2.0.0
Farama-Notifications==0.0.4
fasteners==0.14.1
fastjsonschema==2.18.1
filelock==3.7.1
flake8==4.0.1
flake8-blind-except==0.2.1
flake8-builtins==1.5.3
flake8-commas==2.1.0
flake8-debugger==4.1.2
flake8-docstrings==1.6.0
flake8-isort==4.1.2.post0
fonttools==4.43.1
frozenlist==1.4.0
fsspec==2023.6.0
future==0.18.2
gitdb==4.0.11
GitPython==3.1.40
google-auth==2.23.3
google-auth-oauthlib==0.4.6
greenlet==3.0.0
grpcio==1.43.0
gym==0.21.0
gymnasium==0.29.1
httplib2==0.20.2
huggingface-hub==0.18.0
huggingface-sb3==3.0
hypothesis==6.54.6
identify==2.5.30
idna==3.3
imitation==0.4.0
importlab==0.8.1
importlib-metadata==4.13.0
importlib-resources==6.1.0
iniconfig==2.0.0
ipykernel==6.15.3
ipython==8.16.1
ipython-genutils==0.2.0
ipywidgets==8.1.1
isort==5.12.0
jedi==0.19.1
jeepney==0.7.1
Jinja2==3.1.2
joblib==1.3.2
jsonpickle==3.0.2
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.2
jupyter-server==1.24.0
jupyter-server-mathjax==0.2.6
jupyter_core==5.4.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
keyring==23.5.0
kiwisolver==1.4.5
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
libcst==1.1.0
lockfile==0.12.2
louis==3.20.0
macaroonbakery==1.3.1
Mako==1.1.3
Markdown==3.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.0
matplotlib-inline==0.1.6
mccabe==0.6.1
mdurl==0.1.2
mistune==3.0.2
monotonic==1.6
more-itertools==8.10.0
mpmath==1.3.0
msgpack==1.0.7
multidict==6.0.4
multiprocess==0.70.15
munch==2.5.0
mypy==0.991
mypy-extensions==1.0.0
nbclassic==1.0.0
nbclient==0.5.13
nbconvert==7.9.2
nbdime==3.2.1
nbformat==5.9.2
nest-asyncio==1.5.8
netifaces==0.11.0
networkx==2.8.3
ninja==1.11.1.1
nodeenv==1.8.0
notebook==6.5.6
notebook_shim==0.2.3
numpy==1.25.2
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.0
olefile==0.46
opencv-python==4.8.1.78
optuna==3.4.0
packaging==23.2
pandas==1.4.4
pandocfilters==1.5.0
paramiko==2.9.3
parso==0.8.3
pathspec==0.11.2
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
pip==22.0.2
platformdirs==3.11.0
pluggy==1.3.0
pre-commit==3.5.0
prometheus-client==0.17.1
promise==2.3
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py-cpuinfo==9.0.0
pyarrow==13.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycairo==1.20.1
pycodestyle==2.8.0
pycparser==2.21
pycups==2.0.1
pydocstyle==6.3.0
pydot==1.4.2
pyflakes==2.4.0
pygame==2.5.2
pyglet==1.5.27
Pygments==2.16.1
PyGObject==3.42.1
PyJWT==2.3.0
pymacaroons==0.13.0
PyNaCl==1.5.0
pyparsing==2.4.7
pyRFC3339==1.1
pytest==7.1.3
pytest-cov==3.0.0
pytest-forked==1.6.0
pytest-xdist==2.5.0
pytest_notebook==0.8.0
python-apt==2.4.0+ubuntu2
python-dateutil==2.8.2
python-debian==0.1.43+ubuntu1.1
pytype==2022.7.26
pytz==2022.1
pyxdg==0.27
PyYAML==6.0.1
pyzmq==24.0.1
qtconsole==5.4.4
QtPy==2.4.0
ray==2.0.1
referencing==0.30.2
reportlab==3.6.8
requests==2.25.1
requests-oauthlib==1.3.1
rich==13.6.0
rpds-py==0.10.6
rsa==4.9
sacred==0.8.4
scikit-learn==1.3.1
scipy==1.9.3
screen-resolution-extra==0.0.0
seals==0.2.1
SecretStorage==3.3.1
Send2Trash==1.8.2
sentry-sdk==1.32.0
setproctitle==1.3.3
setuptools==59.6.0
setuptools-scm==7.0.5
shortuuid==1.0.11
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.5
SQLAlchemy==2.0.22
stable-baselines3==2.1.0
stack-data==0.6.3
sympy==1.12
systemd-python==234
tabulate==0.9.0
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.6.2.2
terminado==0.17.1
threadpoolctl==3.2.0
tinycss2==1.2.1
tokenize-rt==5.2.0
toml==0.10.2
tomli==2.0.1
torch==2.1.0
tornado==6.3.3
tqdm==4.66.1
traitlets==5.11.2
triton==2.1.0
typing-inspect==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==2.0.7
usb-creator==0.3.7
virtualenv==20.21.1
wadllib==1.3.6
wandb==0.12.21
wasabi==1.1.2
wcwidth==0.2.8
webencodings==0.5.1
websocket-client==1.6.4
Werkzeug==3.0.0
wheel==0.37.1
widgetsnbextension==4.0.9
wrapt==1.15.0
xdg==5
xkit==0.0.0
xxhash==3.4.1
yarl==1.9.2
zipp==1.0.0

**Comment by imamnurby** [comment]
I got the same error with python 3.9

**Comment by ernestum** [comment]
Should be fixed in v1.0.0. Please repoen if you can reproduce it with the newest version of `imitation`.
