### ISSUE TITLE
airl works poorer than gail on cartpole?

### ISSUE THREAD

**Issue by 1576012404** [HumanCompatibleAI/imitation#84]
airl works poorer than gail on cartpole when i the command with the default parameters?

**Comment by shwang** [comment]
Hello, thanks for pointing this out.

Last time we compared these two, AIRL seemed slower and less stable than GAIL: See https://github.com/HumanCompatibleAI/imitation/pull/33#issuecomment-510255398.

If you have plots available could you please share them?
