### ISSUE TITLE
[priority] Make experiments & tests reproducible

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/imitation#9]
Need to add seeds to all experiment configs. Things that need to be seeded include at least:
  - TensorFlow (for discriminator / reward networks)
  - Stable Baselines (for generator; creates it's own TF session)
  - NumPy
  - Gym environment
  - Gym action spaces (if we're sampling)
Things that I'm not sure we need but won't hurt:
  - Python RNG

**Comment by AdamGleave** [comment]
Right now the tests seem to be failing around 20-30% of the time. Given that we test a variety of different Python versions, this means most builds fail. Working around this for now by retrying the commits, but we should really fix this ASAP before making any more changes to the code.

Apart from making the tests deterministic, it'd also be nice to make them less fragile -- I'm not sure how confident I am in a test if it fails for many choices of seed. But this is lower priority.

**Comment by wichersn** [comment]
I don't think having the same seed every time the tests run is a good idea. If airl training is broken, then `test_train_gen_degrade_D` will pass for 50% of random seeds. So if we always use the same seed, there is a 50% chance that the test won't catch the bug no matter how many times we run the test.

What would work better is to chose 10 or so seeds that we know work and randomly chose one at the beginning of the test.

**Comment by AdamGleave** [comment]
You're right. We should either choose randomly from a set of known-good seeds or make the tests have a lower than 50% chance of passing at random (e.g. require a certain % decrease in loss).

**Comment by AdamGleave** [comment]
Test suite is no longer flaky. Experiments seem pretty replicable in practice, although I'm not confident we're seeding every last source of randomness (e.g. observation/action space) reliably. Closing as lingering randomness does not seem to be causing problems and is best tracked in a different issue.
